package meta

import (
	"context"
	"fmt"
	"time"
)

// Monthly RANGE partitioning for the volume tables — ADR-0079 §2, phase P3.
//
// POSTGRES ONLY. sqlite stays unpartitioned and always will: it is a
// single-writer file with no partitioning of its own, and the volume problem
// this solves belongs to an installation big enough to be on postgres. This is
// the first real per-engine DDL divergence in the runner beyond type names.
//
// WHICH TABLES, and why only these two. `script_history` and `audit_log` are
// the VOLUME class from ADR-0079 §1: one row per statement, FK leaves (nothing
// REFERENCES them), no cross-row uniqueness beyond their surrogate id. The
// correctness tables — `tx_outcomes`, `tx_pending` — are NOT partitioned, and
// that is not an omission: the ADR measured that time-range partitioning
// `tx_outcomes` DESTROYS both of R4's durable guards, because postgres forces
// the partition key into every unique index and the same (tx_id, seq) can then
// be rewritten in a different month.
//
// THE COST, stated because it is easy to miss: `PRIMARY KEY (id, started_at)`
// does NOT make `id` unique. Postgres requires the partition key in every
// unique constraint, so `id` survives as a global key only by the parent
// sequence and by migration discipline — never by the schema. Everything that
// treats `id` as an identity is on notice, and the id-integrity tests exist
// for exactly that.

// partitionedTable describes one table's conversion.
type partitionedTable struct {
	name    string
	timeCol string // the partition key, unix SECONDS
	// create is the partitioned parent's definition, minus the PRIMARY KEY
	// and the PARTITION BY clause, which are generated.
	columns string
	indexes []string
}

// volumeTables is the partition plan.
//
// A list rather than scattered DDL, so "which tables are partitioned" has one
// answer that a reader can check against ADR-0079 §1's classifier rule.
var volumeTables = []partitionedTable{
	{
		name:    "script_history",
		timeCol: "started_at",
		columns: `id BIGINT GENERATED BY DEFAULT AS IDENTITY,
		user_id BIGINT NOT NULL REFERENCES users(id),
		connection_id BIGINT NOT NULL REFERENCES connections(id),
		ip TEXT NOT NULL,
		script TEXT NOT NULL,
		started_at BIGINT NOT NULL,
		duration_ms BIGINT NOT NULL DEFAULT 0,
		row_count BIGINT NOT NULL DEFAULT 0,
		status TEXT NOT NULL,
		error TEXT NOT NULL DEFAULT '',
		tx_id TEXT NOT NULL DEFAULT ''`,
		indexes: []string{
			`CREATE INDEX idx_history_user ON script_history(user_id, started_at)`,
			`CREATE INDEX idx_history_tx ON script_history(tx_id)`,
			`CREATE INDEX idx_history_status ON script_history(status)`,
		},
	},
	{
		name:    "audit_log",
		timeCol: "created_at",
		// audit_log has NO foreign keys by design: auditing must never fail,
		// and user_id 0 records pre-auth events (ADR-0053 §2). Partitioning
		// does not change that.
		columns: `id BIGINT GENERATED BY DEFAULT AS IDENTITY,
		user_id BIGINT NOT NULL DEFAULT 0,
		ip TEXT NOT NULL DEFAULT '',
		action TEXT NOT NULL,
		detail TEXT NOT NULL DEFAULT '',
		created_at BIGINT NOT NULL,
		tx_id TEXT NOT NULL DEFAULT ''`,
		indexes: []string{
			`CREATE INDEX idx_audit_created ON audit_log(created_at)`,
			`CREATE INDEX idx_audit_tx ON audit_log(tx_id)`,
		},
	},
}

// monthStart truncates t to the first instant of its month, UTC.
//
// Every month step MUST start from this rather than from the raw clock.
// AddDate normalises overflow, so 31 January plus one month is 3 MARCH — a
// look-ahead loop stepping from an unnormalised `now` skips February entirely
// on the 29th, 30th and 31st of January, and skips other months from the 31st.
// The partition for the skipped month is then never created, its rows land in
// DEFAULT, and before the adoption path in ensurePartition that was
// unrecoverable. Three days a year, silently.
func monthStart(t time.Time) time.Time {
	u := t.UTC()
	return time.Date(u.Year(), u.Month(), 1, 0, 0, 0, 0, time.UTC)
}

// monthBounds returns the [start, end) unix-second bounds of t's month, UTC.
//
// UTC deliberately: a partition boundary that moved with the server's timezone
// would put the same row in different months on two hosts, and the retention
// question ("is this month droppable?") would have two answers.
func monthBounds(t time.Time) (start, end int64) {
	s := monthStart(t)
	return s.Unix(), s.AddDate(0, 1, 0).Unix()
}

// partitionName is the child table's name for a month.
func partitionName(table string, t time.Time) string {
	return fmt.Sprintf("%s_p%s", table, t.UTC().Format("2006_01"))
}

// convertToPartitioned rebuilds a table as a monthly-partitioned one, carrying
// its rows across.
//
// Postgres cannot ALTER a table into a partitioned one, so this is
// rename-create-copy-drop. It runs inside the upgrade's single transaction, so
// a failure anywhere leaves the original table untouched under its original
// name — there is no half-converted state to recover from.
func convertToPartitioned(ctx context.Context, ex migExec, p partitionedTable, now time.Time) error {
	old := p.name + "_unpart"
	if _, err := ex.ExecContext(ctx, fmt.Sprintf(
		`ALTER TABLE %s RENAME TO %s`, p.name, old)); err != nil {
		return fmt.Errorf("renaming %s: %w", p.name, err)
	}
	if _, err := ex.ExecContext(ctx, fmt.Sprintf(
		`CREATE TABLE %s (%s, PRIMARY KEY (id, %s)) PARTITION BY RANGE (%s)`,
		p.name, p.columns, p.timeCol, p.timeCol)); err != nil {
		return fmt.Errorf("creating the partitioned %s: %w", p.name, err)
	}

	// A DEFAULT partition catches anything outside an explicit month.
	//
	// It is a safety net, not the plan: rows landing here are rows no monthly
	// partition claimed, which means the roll fell behind. Without it such an
	// insert would FAIL, and an audit write that fails is worse than an audit
	// write in the wrong child table.
	if _, err := ex.ExecContext(ctx, fmt.Sprintf(
		`CREATE TABLE %s_pdefault PARTITION OF %s DEFAULT`, p.name, p.name)); err != nil {
		return fmt.Errorf("creating the default partition for %s: %w", p.name, err)
	}

	// Every month the EXISTING rows fall in needs a partition before the copy
	// — this is the part static SQL cannot express, because the answer is in
	// the data. Rows would otherwise all land in DEFAULT, and a later attempt
	// to create those months would fail on overlapping default rows.
	months, err := existingMonths(ctx, ex, old, p.timeCol)
	if err != nil {
		return err
	}
	// Current plus the look-ahead, stepped from the month START so a
	// conversion run on the 31st does not skip the next month (see monthStart).
	base := monthStart(now)
	for i := 0; i <= partitionLookAhead; i++ {
		months = append(months, base.AddDate(0, i, 0))
	}
	for _, m := range months {
		if err := ensurePartition(ctx, ex, p, m); err != nil {
			return err
		}
	}

	if _, err := ex.ExecContext(ctx, fmt.Sprintf(
		`INSERT INTO %s SELECT * FROM %s`, p.name, old)); err != nil {
		return fmt.Errorf("copying rows into the partitioned %s: %w", p.name, err)
	}
	// The identity sequence starts at 1 on the new table; without this the
	// next insert collides with a copied id. Nothing else re-derives it, so
	// the whole id story rests on this line (ADR-0079 §2's discipline note).
	if _, err := ex.ExecContext(ctx, fmt.Sprintf(
		`SELECT setval(pg_get_serial_sequence('%s','id'),
		    GREATEST(COALESCE((SELECT MAX(id) FROM %s),0),1),
		    COALESCE((SELECT MAX(id) FROM %s),0) > 0)`, p.name, p.name, p.name)); err != nil {
		return fmt.Errorf("advancing the %s id sequence: %w", p.name, err)
	}
	if _, err := ex.ExecContext(ctx, fmt.Sprintf(`DROP TABLE %s`, old)); err != nil {
		return fmt.Errorf("dropping %s: %w", old, err)
	}
	for _, idx := range p.indexes {
		if _, err := ex.ExecContext(ctx, idx); err != nil {
			return fmt.Errorf("recreating an index on %s: %w", p.name, err)
		}
	}
	return nil
}

// existingMonths reports the distinct months present in a table.
func existingMonths(ctx context.Context, ex migExec, table, timeCol string) ([]time.Time, error) {
	rows, err := ex.QueryContext(ctx, fmt.Sprintf(
		`SELECT DISTINCT date_trunc('month', to_timestamp(%s) AT TIME ZONE 'UTC') FROM %s`,
		timeCol, table))
	if err != nil {
		return nil, fmt.Errorf("reading the months present in %s: %w", table, err)
	}
	defer func() { _ = rows.Close() }()
	var out []time.Time
	for rows.Next() {
		var t time.Time
		if err := rows.Scan(&t); err != nil {
			return nil, fmt.Errorf("reading a month from %s: %w", table, err)
		}
		out = append(out, t)
	}
	return out, rows.Err()
}

// ensurePartition creates one month's child table if it is absent, ADOPTING
// any rows for that month that have already landed in DEFAULT.
//
// The adoption is the load-bearing half, and it was missing (lector's PR #32
// r0 MF2). Postgres refuses to create a partition whose range overlaps rows
// sitting in the default partition:
//
//	ERROR: updated partition constraint for default partition
//	"audit_log_pdefault" would be violated by some row (SQLSTATE 23514)
//
// So without adoption the DEFAULT partition is not a safety net — it is a
// TRAP. One missed roll puts a row for that month in DEFAULT, and from then on
// every attempt to create that month FAILS. Writes keep landing in DEFAULT,
// the daily roll logs the same error forever, and the month can never be
// detached for retention because its rows are not in it. A transient miss
// becomes permanent, and each further month compounds it rather than healing.
//
// That inverts the tradeoff the default partition was chosen for. The argument
// for it — an audit write that FAILS is worse than one in the wrong child
// table — holds only while "the wrong child table" stays recoverable.
//
// IF NOT EXISTS stays on the plain path: the roll runs at startup AND on a
// ticker, and both may reach the same month, so creating it twice must be a
// no-op rather than a startup failure.
func ensurePartition(ctx context.Context, ex migExec, p partitionedTable, month time.Time) error {
	start, end := monthBounds(month)
	name := partitionName(p.name, month)

	// Already there — the steady state, and one cheap catalog lookup.
	exists, err := relationExists(ctx, ex, name)
	if err != nil {
		return err
	}
	if exists {
		return nil
	}

	// Are there rows in DEFAULT this partition would have to claim? Asked
	// BEFORE creating rather than after a failure, because a failed statement
	// aborts the surrounding transaction and this runs inside one — recovering
	// from the error would need a savepoint to learn what one query answers.
	stranded, err := defaultHoldsRange(ctx, ex, p, start, end)
	if err != nil {
		return err
	}
	if !stranded {
		if _, err := ex.ExecContext(ctx, fmt.Sprintf(
			`CREATE TABLE IF NOT EXISTS %s PARTITION OF %s FOR VALUES FROM (%d) TO (%d)`,
			name, p.name, start, end)); err != nil {
			return fmt.Errorf("creating partition %s: %w", name, err)
		}
		return nil
	}
	return adoptFromDefault(ctx, ex, p, name, start, end)
}

// relationExists reports whether a relation of that name is visible.
func relationExists(ctx context.Context, ex migExec, name string) (bool, error) {
	rows, err := ex.QueryContext(ctx, `SELECT to_regclass($1) IS NOT NULL`, name)
	if err != nil {
		return false, fmt.Errorf("looking up the relation %s: %w", name, err)
	}
	defer func() { _ = rows.Close() }()
	var ok bool
	if rows.Next() {
		if err := rows.Scan(&ok); err != nil {
			return false, err
		}
	}
	return ok, rows.Err()
}

// defaultHoldsRange reports whether the default partition holds any row inside
// [start, end).
func defaultHoldsRange(ctx context.Context, ex migExec, p partitionedTable, start, end int64) (bool, error) {
	def := p.name + "_pdefault"
	exists, err := relationExists(ctx, ex, def)
	if err != nil || !exists {
		return false, err
	}
	rows, err := ex.QueryContext(ctx, fmt.Sprintf(
		`SELECT EXISTS(SELECT 1 FROM %s WHERE %s >= %d AND %s < %d)`,
		def, p.timeCol, start, p.timeCol, end))
	if err != nil {
		return false, fmt.Errorf("checking %s for stranded rows: %w", def, err)
	}
	defer func() { _ = rows.Close() }()
	var found bool
	if rows.Next() {
		if err := rows.Scan(&found); err != nil {
			return false, err
		}
	}
	return found, rows.Err()
}

// adoptFromDefault creates the month's partition and moves the rows stranded
// in DEFAULT into it.
//
// Postgres offers no way to create an overlapping partition in place, so the
// default has to step aside: detach it, create the month, re-insert the rows
// through the PARENT (which now routes them to the new child), delete the
// originals, re-attach. The caller runs this inside a transaction, so a
// failure at any step leaves the default attached and its rows untouched —
// the state before the attempt, never a store with no default partition.
func adoptFromDefault(ctx context.Context, ex migExec, p partitionedTable, name string, start, end int64) error {
	def := p.name + "_pdefault"
	steps := []struct {
		what string
		sql  string
	}{
		{"detaching the default partition", fmt.Sprintf(
			`ALTER TABLE %s DETACH PARTITION %s`, p.name, def)},
		{"creating the month partition", fmt.Sprintf(
			`CREATE TABLE %s PARTITION OF %s FOR VALUES FROM (%d) TO (%d)`,
			name, p.name, start, end)},
		{"re-routing the stranded rows", fmt.Sprintf(
			`INSERT INTO %s SELECT * FROM %s WHERE %s >= %d AND %s < %d`,
			p.name, def, p.timeCol, start, p.timeCol, end)},
		{"clearing the adopted rows from the default", fmt.Sprintf(
			`DELETE FROM %s WHERE %s >= %d AND %s < %d`, def, p.timeCol, start, p.timeCol, end)},
		{"re-attaching the default partition", fmt.Sprintf(
			`ALTER TABLE %s ATTACH PARTITION %s DEFAULT`, p.name, def)},
	}
	for _, s := range steps {
		if _, err := ex.ExecContext(ctx, s.sql); err != nil {
			return fmt.Errorf("adopting stranded %s rows into %s (%s): %w",
				p.name, name, s.what, err)
		}
	}
	return nil
}

// partitionLookAhead is how many months past the current one the roll keeps
// covered.
//
// Three, matching the house convention, rather than the one this shipped with.
// The look-ahead has to exceed the roll interval by a margin, because what it
// buys is survivable MISSES: at three, two consecutive failed rolls still leave
// the current month covered. At one, a single missed roll across a boundary
// strands rows in DEFAULT — which ensurePartition can now recover from, but
// not having to is better than recovering.
const partitionLookAhead = 3

// RollPartitions creates the coming months' partitions if absent.
//
// Called at startup AND on a ticker. Startup alone is not enough: a daemon
// that stays up across a month boundary would find no partition for the new
// month and every audit write would land in DEFAULT — which still succeeds,
// so nothing would fail and nobody would notice until a retention drop tried
// to detach a month whose rows were somewhere else.
//
// It runs in ONE transaction holding an advisory lock, which the adoption path
// in ensurePartition requires: recovering stranded rows detaches the default
// partition, creates the month, moves the rows and re-attaches. Two daemons
// doing that concurrently would race over the detached default, and a crash
// mid-sequence without the transaction would leave the table with NO default
// partition — turning a recoverable state into failed writes.
//
// A no-op on sqlite, so callers do not have to branch on the engine.
func (s *Store) RollPartitions(ctx context.Context, now time.Time) error {
	if s.engine != "postgres" {
		return nil
	}
	tx, err := s.conn.Begin(ctx)
	if err != nil {
		return fmt.Errorf("meta: beginning the partition roll transaction: %w", err)
	}
	committed := false
	defer func() {
		if !committed {
			_ = tx.Rollback()
		}
	}()

	sysID, dbOID, err := serverIdentity(ctx, tx)
	if err != nil {
		return fmt.Errorf("meta: reading the server identity for the partition roll: %w", err)
	}
	if _, err := tx.ExecContext(ctx, "SET LOCAL lock_timeout = '30000ms'"); err != nil {
		return fmt.Errorf("meta: bounding the partition roll lock wait: %w", err)
	}
	// Its own key namespace: a roll must not block, or be blocked by, a
	// migration holding the other lock for a long upgrade.
	if _, err := tx.ExecContext(ctx, "SELECT pg_advisory_xact_lock($1)",
		advisoryKey("autodb-partition-roll", sysID, dbOID)); err != nil {
		return fmt.Errorf("meta: waiting for the partition roll lock: %w", err)
	}

	for _, p := range volumeTables {
		base := monthStart(now)
		for i := 0; i <= partitionLookAhead; i++ {
			if err := ensurePartition(ctx, tx, p, base.AddDate(0, i, 0)); err != nil {
				return err
			}
		}
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("meta: committing the partition roll: %w", err)
	}
	committed = true
	return nil
}

// PartitionNames lists a table's child partitions, oldest first.
//
// Exported for the tests and for an operator answering "what is actually
// there?" — the answer to which is otherwise a catalog query nobody remembers.
func (s *Store) PartitionNames(ctx context.Context, table string) ([]string, error) {
	if s.engine != "postgres" {
		return nil, nil
	}
	rows, err := s.conn.QueryContext(ctx, `
		SELECT c.relname
		FROM pg_inherits i
		JOIN pg_class c ON c.oid = i.inhrelid
		JOIN pg_class p ON p.oid = i.inhparent
		WHERE p.relname = $1
		ORDER BY c.relname`, table)
	if err != nil {
		return nil, fmt.Errorf("meta: listing partitions of %s: %w", table, err)
	}
	defer func() { _ = rows.Close() }()
	var out []string
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err != nil {
			return nil, err
		}
		out = append(out, n)
	}
	return out, rows.Err()
}

// CheckLogicalIDUniqueness verifies that `id` is still a global key.
//
// It has to be CHECKED because the schema no longer guarantees it. Postgres
// requires the partition key in every unique constraint, so the primary key
// became (id, started_at) — which permits the SAME id in two months and
// accepts it silently. `id` survives as a logical key only by the parent
// sequence and by migration discipline.
//
// Two things depend on that and would fail quietly rather than loudly:
//
//   - a by-id read has no defined answer when two partitions hold the id;
//   - R4's repairPendingHistory pages with OrderBy(id) + Gt(id, cursor), so a
//     non-monotonic id lets a row be SKIPPED — the same starvation class as
//     PR #20 r2/r3, reintroduced by the storage layout rather than the loop.
//
// So this runs as a preflight and REFUSES, rather than leaving the duplicate
// to be discovered by whichever of those two misbehaves first.
//
// Trivially clean on sqlite, whose id is a plain primary key.
func (s *Store) CheckLogicalIDUniqueness(ctx context.Context) error {
	if s.engine != "postgres" {
		return nil
	}
	for _, p := range volumeTables {
		rows, err := s.conn.QueryContext(ctx, fmt.Sprintf(
			`SELECT id, count(*) FROM %s GROUP BY id HAVING count(*) > 1 ORDER BY id LIMIT 5`,
			p.name))
		if err != nil {
			return fmt.Errorf("meta: checking id uniqueness on %s: %w", p.name, err)
		}
		var dups []string
		for rows.Next() {
			var id, n int64
			if err := rows.Scan(&id, &n); err != nil {
				_ = rows.Close()
				return err
			}
			dups = append(dups, fmt.Sprintf("id %d appears %d times", id, n))
		}
		cerr := rows.Close()
		if err := rows.Err(); err != nil {
			return err
		}
		if cerr != nil {
			return cerr
		}
		if len(dups) > 0 {
			return fmt.Errorf("meta: %s holds duplicate logical ids across partitions (%s). "+
				"PRIMARY KEY (id, %s) does not make id unique — it survives only by the "+
				"parent sequence — and a by-id read is undefined while this holds",
				p.name, joinStrings(dups, "; "), p.timeCol)
		}
	}
	return nil
}

func joinStrings(in []string, sep string) string {
	out := ""
	for i, s := range in {
		if i > 0 {
			out += sep
		}
		out += s
	}
	return out
}

// maxPrepartitionMonths bounds how many months a migration will pre-create.
//
// A store with a corrupt timestamp — a row at unix epoch 0, say — would
// otherwise ask for six hundred years of partitions. The cap keeps a bad row
// from turning a migration into a catalog flood; rows older than the covered
// span still arrive safely, they just land in DEFAULT, which ensurePartition
// can now adopt them out of.
const maxPrepartitionMonths = 600

// prepartitionForSource creates destination partitions covering every month
// the SOURCE's volume tables actually span, before the copy runs.
//
// Without this the migration copies years of history into a destination whose
// only partitions are the current month and its look-ahead, so EVERY
// historical audit and history row lands in DEFAULT (Johno, 2026-09-01). That
// is bad on its own — those months can never be detached for retention because
// their rows are not in them — and it used to be unrecoverable, since a
// partition cannot be created over rows already sitting in DEFAULT. The
// adoption path in ensurePartition would now dig it back out one month at a
// time, but a migration that needs digging out is a migration done wrong.
//
// The months come from the source's own MIN/MAX rather than from a fixed
// window, for the same reason the v11 conversion computes its months: the
// answer is in the data, and no static window knows how far back a store goes.
//
// A no-op unless the destination is postgres.
func prepartitionForSource(ctx context.Context, src, dst *Store) error {
	if dst.engine != "postgres" {
		return nil
	}
	for _, p := range volumeTables {
		lo, hi, ok, err := timeSpan(ctx, src.conn, p)
		if err != nil {
			return err
		}
		if !ok {
			continue // no rows: the roll's own months are enough
		}
		first, last := monthStart(time.Unix(lo, 0)), monthStart(time.Unix(hi, 0))
		// Walk back from the newest month so that a span past the cap keeps
		// the RECENT history — the part anyone is going to query — and leaves
		// only the oldest rows for DEFAULT.
		var months []time.Time
		for m := last; !m.Before(first) && len(months) < maxPrepartitionMonths; m = m.AddDate(0, -1, 0) {
			months = append(months, m)
		}
		for _, m := range months {
			if err := ensurePartition(ctx, dst.conn, p, m); err != nil {
				return fmt.Errorf("%w: preparing the destination for %s history: %v",
					ErrMigrate, p.name, err)
			}
		}
	}
	return nil
}

// timeSpan reports the [min, max] of a table's partition-key column, and
// whether the table had any rows at all.
func timeSpan(ctx context.Context, ex migExec, p partitionedTable) (lo, hi int64, ok bool, err error) {
	rows, qerr := ex.QueryContext(ctx, fmt.Sprintf(
		`SELECT MIN(%s), MAX(%s) FROM %s`, p.timeCol, p.timeCol, p.name))
	if qerr != nil {
		return 0, 0, false, fmt.Errorf("reading the %s time span: %w", p.name, qerr)
	}
	defer func() { _ = rows.Close() }()
	if rows.Next() {
		// NULL on both when the table is empty.
		var lov, hiv *int64
		if serr := rows.Scan(&lov, &hiv); serr != nil {
			return 0, 0, false, serr
		}
		if lov != nil && hiv != nil {
			return *lov, *hiv, true, rows.Err()
		}
	}
	return 0, 0, false, rows.Err()
}
