package meta

import (
	"context"
	"fmt"
	"time"
)

// Monthly RANGE partitioning for the volume tables — ADR-0079 §2, phase P3.
//
// POSTGRES ONLY. sqlite stays unpartitioned and always will: it is a
// single-writer file with no partitioning of its own, and the volume problem
// this solves belongs to an installation big enough to be on postgres. This is
// the first real per-engine DDL divergence in the runner beyond type names.
//
// WHICH TABLES, and why only these two. `script_history` and `audit_log` are
// the VOLUME class from ADR-0079 §1: one row per statement, FK leaves (nothing
// REFERENCES them), no cross-row uniqueness beyond their surrogate id. The
// correctness tables — `tx_outcomes`, `tx_pending` — are NOT partitioned, and
// that is not an omission: the ADR measured that time-range partitioning
// `tx_outcomes` DESTROYS both of R4's durable guards, because postgres forces
// the partition key into every unique index and the same (tx_id, seq) can then
// be rewritten in a different month.
//
// THE COST, stated because it is easy to miss: `PRIMARY KEY (id, started_at)`
// does NOT make `id` unique. Postgres requires the partition key in every
// unique constraint, so `id` survives as a global key only by the parent
// sequence and by migration discipline — never by the schema. Everything that
// treats `id` as an identity is on notice, and the id-integrity tests exist
// for exactly that.

// partitionedTable describes one table's conversion.
type partitionedTable struct {
	name    string
	timeCol string // the partition key, unix SECONDS
	// create is the partitioned parent's definition, minus the PRIMARY KEY
	// and the PARTITION BY clause, which are generated.
	columns string
	indexes []string
}

// volumeTables is the partition plan.
//
// A list rather than scattered DDL, so "which tables are partitioned" has one
// answer that a reader can check against ADR-0079 §1's classifier rule.
var volumeTables = []partitionedTable{
	{
		name:    "script_history",
		timeCol: "started_at",
		columns: `id BIGINT GENERATED BY DEFAULT AS IDENTITY,
		user_id BIGINT NOT NULL REFERENCES users(id),
		connection_id BIGINT NOT NULL REFERENCES connections(id),
		ip TEXT NOT NULL,
		script TEXT NOT NULL,
		started_at BIGINT NOT NULL,
		duration_ms BIGINT NOT NULL DEFAULT 0,
		row_count BIGINT NOT NULL DEFAULT 0,
		status TEXT NOT NULL,
		error TEXT NOT NULL DEFAULT '',
		tx_id TEXT NOT NULL DEFAULT ''`,
		indexes: []string{
			`CREATE INDEX idx_history_user ON script_history(user_id, started_at)`,
			`CREATE INDEX idx_history_tx ON script_history(tx_id)`,
			`CREATE INDEX idx_history_status ON script_history(status)`,
		},
	},
	{
		name:    "audit_log",
		timeCol: "created_at",
		// audit_log has NO foreign keys by design: auditing must never fail,
		// and user_id 0 records pre-auth events (ADR-0053 §2). Partitioning
		// does not change that.
		columns: `id BIGINT GENERATED BY DEFAULT AS IDENTITY,
		user_id BIGINT NOT NULL DEFAULT 0,
		ip TEXT NOT NULL DEFAULT '',
		action TEXT NOT NULL,
		detail TEXT NOT NULL DEFAULT '',
		created_at BIGINT NOT NULL,
		tx_id TEXT NOT NULL DEFAULT ''`,
		indexes: []string{
			`CREATE INDEX idx_audit_created ON audit_log(created_at)`,
			`CREATE INDEX idx_audit_tx ON audit_log(tx_id)`,
		},
	},
}

// monthBounds returns the [start, end) unix-second bounds of t's month, UTC.
//
// UTC deliberately: a partition boundary that moved with the server's timezone
// would put the same row in different months on two hosts, and the retention
// question ("is this month droppable?") would have two answers.
func monthBounds(t time.Time) (start, end int64) {
	u := t.UTC()
	s := time.Date(u.Year(), u.Month(), 1, 0, 0, 0, 0, time.UTC)
	return s.Unix(), s.AddDate(0, 1, 0).Unix()
}

// partitionName is the child table's name for a month.
func partitionName(table string, t time.Time) string {
	return fmt.Sprintf("%s_p%s", table, t.UTC().Format("2006_01"))
}

// convertToPartitioned rebuilds a table as a monthly-partitioned one, carrying
// its rows across.
//
// Postgres cannot ALTER a table into a partitioned one, so this is
// rename-create-copy-drop. It runs inside the upgrade's single transaction, so
// a failure anywhere leaves the original table untouched under its original
// name — there is no half-converted state to recover from.
func convertToPartitioned(ctx context.Context, ex migExec, p partitionedTable, now time.Time) error {
	old := p.name + "_unpart"
	if _, err := ex.ExecContext(ctx, fmt.Sprintf(
		`ALTER TABLE %s RENAME TO %s`, p.name, old)); err != nil {
		return fmt.Errorf("renaming %s: %w", p.name, err)
	}
	if _, err := ex.ExecContext(ctx, fmt.Sprintf(
		`CREATE TABLE %s (%s, PRIMARY KEY (id, %s)) PARTITION BY RANGE (%s)`,
		p.name, p.columns, p.timeCol, p.timeCol)); err != nil {
		return fmt.Errorf("creating the partitioned %s: %w", p.name, err)
	}

	// A DEFAULT partition catches anything outside an explicit month.
	//
	// It is a safety net, not the plan: rows landing here are rows no monthly
	// partition claimed, which means the roll fell behind. Without it such an
	// insert would FAIL, and an audit write that fails is worse than an audit
	// write in the wrong child table.
	if _, err := ex.ExecContext(ctx, fmt.Sprintf(
		`CREATE TABLE %s_pdefault PARTITION OF %s DEFAULT`, p.name, p.name)); err != nil {
		return fmt.Errorf("creating the default partition for %s: %w", p.name, err)
	}

	// Every month the EXISTING rows fall in needs a partition before the copy
	// — this is the part static SQL cannot express, because the answer is in
	// the data. Rows would otherwise all land in DEFAULT, and a later attempt
	// to create those months would fail on overlapping default rows.
	months, err := existingMonths(ctx, ex, old, p.timeCol)
	if err != nil {
		return err
	}
	months = append(months, now, now.AddDate(0, 1, 0)) // current and next
	for _, m := range months {
		if err := ensurePartition(ctx, ex, p, m); err != nil {
			return err
		}
	}

	if _, err := ex.ExecContext(ctx, fmt.Sprintf(
		`INSERT INTO %s SELECT * FROM %s`, p.name, old)); err != nil {
		return fmt.Errorf("copying rows into the partitioned %s: %w", p.name, err)
	}
	// The identity sequence starts at 1 on the new table; without this the
	// next insert collides with a copied id. Nothing else re-derives it, so
	// the whole id story rests on this line (ADR-0079 §2's discipline note).
	if _, err := ex.ExecContext(ctx, fmt.Sprintf(
		`SELECT setval(pg_get_serial_sequence('%s','id'),
		    GREATEST(COALESCE((SELECT MAX(id) FROM %s),0),1),
		    COALESCE((SELECT MAX(id) FROM %s),0) > 0)`, p.name, p.name, p.name)); err != nil {
		return fmt.Errorf("advancing the %s id sequence: %w", p.name, err)
	}
	if _, err := ex.ExecContext(ctx, fmt.Sprintf(`DROP TABLE %s`, old)); err != nil {
		return fmt.Errorf("dropping %s: %w", old, err)
	}
	for _, idx := range p.indexes {
		if _, err := ex.ExecContext(ctx, idx); err != nil {
			return fmt.Errorf("recreating an index on %s: %w", p.name, err)
		}
	}
	return nil
}

// existingMonths reports the distinct months present in a table.
func existingMonths(ctx context.Context, ex migExec, table, timeCol string) ([]time.Time, error) {
	rows, err := ex.QueryContext(ctx, fmt.Sprintf(
		`SELECT DISTINCT date_trunc('month', to_timestamp(%s) AT TIME ZONE 'UTC') FROM %s`,
		timeCol, table))
	if err != nil {
		return nil, fmt.Errorf("reading the months present in %s: %w", table, err)
	}
	defer func() { _ = rows.Close() }()
	var out []time.Time
	for rows.Next() {
		var t time.Time
		if err := rows.Scan(&t); err != nil {
			return nil, fmt.Errorf("reading a month from %s: %w", table, err)
		}
		out = append(out, t)
	}
	return out, rows.Err()
}

// ensurePartition creates one month's child table if it is absent.
//
// IF NOT EXISTS on purpose: the roll runs at startup and on a ticker, and both
// may reach the same month. Creating it twice must be a no-op rather than a
// startup failure.
func ensurePartition(ctx context.Context, ex migExec, p partitionedTable, month time.Time) error {
	start, end := monthBounds(month)
	name := partitionName(p.name, month)
	_, err := ex.ExecContext(ctx, fmt.Sprintf(
		`CREATE TABLE IF NOT EXISTS %s PARTITION OF %s FOR VALUES FROM (%d) TO (%d)`,
		name, p.name, start, end))
	if err != nil {
		return fmt.Errorf("creating partition %s: %w", name, err)
	}
	return nil
}

// RollPartitions creates the current and next month's partitions if absent.
//
// Called at startup AND on a ticker. Startup alone is not enough: a daemon
// that stays up across a month boundary would find no partition for the new
// month and every audit write would land in DEFAULT — which still succeeds,
// so nothing would fail and nobody would notice until a retention drop tried
// to detach a month whose rows were somewhere else.
//
// "Current and next" rather than just current, so the boundary is crossed with
// the partition already in place rather than in the same instant the clock
// rolls over.
//
// A no-op on sqlite, so callers do not have to branch on the engine.
func (s *Store) RollPartitions(ctx context.Context, now time.Time) error {
	if s.engine != "postgres" {
		return nil
	}
	for _, p := range volumeTables {
		for _, m := range []time.Time{now, now.AddDate(0, 1, 0)} {
			if err := ensurePartition(ctx, s.conn, p, m); err != nil {
				return err
			}
		}
	}
	return nil
}

// PartitionNames lists a table's child partitions, oldest first.
//
// Exported for the tests and for an operator answering "what is actually
// there?" — the answer to which is otherwise a catalog query nobody remembers.
func (s *Store) PartitionNames(ctx context.Context, table string) ([]string, error) {
	if s.engine != "postgres" {
		return nil, nil
	}
	rows, err := s.conn.QueryContext(ctx, `
		SELECT c.relname
		FROM pg_inherits i
		JOIN pg_class c ON c.oid = i.inhrelid
		JOIN pg_class p ON p.oid = i.inhparent
		WHERE p.relname = $1
		ORDER BY c.relname`, table)
	if err != nil {
		return nil, fmt.Errorf("meta: listing partitions of %s: %w", table, err)
	}
	defer func() { _ = rows.Close() }()
	var out []string
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err != nil {
			return nil, err
		}
		out = append(out, n)
	}
	return out, rows.Err()
}

// CheckLogicalIDUniqueness verifies that `id` is still a global key.
//
// It has to be CHECKED because the schema no longer guarantees it. Postgres
// requires the partition key in every unique constraint, so the primary key
// became (id, started_at) — which permits the SAME id in two months and
// accepts it silently. `id` survives as a logical key only by the parent
// sequence and by migration discipline.
//
// Two things depend on that and would fail quietly rather than loudly:
//
//   - a by-id read has no defined answer when two partitions hold the id;
//   - R4's repairPendingHistory pages with OrderBy(id) + Gt(id, cursor), so a
//     non-monotonic id lets a row be SKIPPED — the same starvation class as
//     PR #20 r2/r3, reintroduced by the storage layout rather than the loop.
//
// So this runs as a preflight and REFUSES, rather than leaving the duplicate
// to be discovered by whichever of those two misbehaves first.
//
// Trivially clean on sqlite, whose id is a plain primary key.
func (s *Store) CheckLogicalIDUniqueness(ctx context.Context) error {
	if s.engine != "postgres" {
		return nil
	}
	for _, p := range volumeTables {
		rows, err := s.conn.QueryContext(ctx, fmt.Sprintf(
			`SELECT id, count(*) FROM %s GROUP BY id HAVING count(*) > 1 ORDER BY id LIMIT 5`,
			p.name))
		if err != nil {
			return fmt.Errorf("meta: checking id uniqueness on %s: %w", p.name, err)
		}
		var dups []string
		for rows.Next() {
			var id, n int64
			if err := rows.Scan(&id, &n); err != nil {
				_ = rows.Close()
				return err
			}
			dups = append(dups, fmt.Sprintf("id %d appears %d times", id, n))
		}
		cerr := rows.Close()
		if err := rows.Err(); err != nil {
			return err
		}
		if cerr != nil {
			return cerr
		}
		if len(dups) > 0 {
			return fmt.Errorf("meta: %s holds duplicate logical ids across partitions (%s). "+
				"PRIMARY KEY (id, %s) does not make id unique — it survives only by the "+
				"parent sequence — and a by-id read is undefined while this holds",
				p.name, joinStrings(dups, "; "), p.timeCol)
		}
	}
	return nil
}

func joinStrings(in []string, sep string) string {
	out := ""
	for i, s := range in {
		if i > 0 {
			out += sep
		}
		out += s
	}
	return out
}
