package frontdoor

// THE UNNAMED PREPARED STATEMENT A lib/pq SESSION LEAVES BEHIND, AND THE BIND
// THAT MUST STILL FIND IT.
//
// What must hold: after a lib/pq client runs a query that carries an argument
// and the front door has answered ReadyForQuery with the idle status, the
// client may send a Bind naming the unnamed prepared statement WITHOUT sending
// a new Parse first, and that Bind must succeed. What goes wrong otherwise:
// the front door answers 26000 — invalid_sql_statement_name — for a statement
// the client correctly believes is live, which is the front door inventing a
// client bug. A driver's recovery for 26000 is "re-Parse and try again", so
// the invented error does not even surface as a fault; it surfaces as silent
// extra round trips, or as a failed query on a driver that does not recover.
//
// WHY THIS DRIVER AND NOT A HAND-BUILT FRAME SEQUENCE. lib/pq's query path,
// when the call carries arguments, prepares into the EMPTY statement name and
// then discards its own handle: the only code in lib/pq that writes Close(S)
// is the statement's own Close method, and database/sql reaches that only for
// statements obtained through Prepare, which are given generated NAMES. So
// nothing ever closes the unnamed one. That is a fact about the driver Label
// Manager actually deploys, and a hand-built Parse/Bind pair would prove the
// front door tolerates a shape without proving any real client produces it.
//
// WHY THE OBVIOUS ALTERNATIVE IS WRONG. The tempting reading is that the
// session is clean again because the driver re-parses the unnamed statement on
// its next call, so nothing accumulates. Replacing a statement is not emptying
// it: between the two calls the statement is live on the backend, the client is
// entitled to bind it, and a scheduler that treated the session as empty would
// have released and reset the backend underneath a client that had done nothing
// wrong. The Bind below is what that entitlement looks like on the wire.
//
// HOW THE FRAMES ARE SEEN AT ALL. The front door has no plaintext path, so a
// tap placed between lib/pq and the listener would see ciphertext. This puts
// the tap where the plaintext is instead: a local relay that lib/pq connects to
// in the clear and that speaks TLS to the real listener. The relay forwards
// whole frames in both directions and records them, and when the test takes
// over it stops relaying and keeps the SAME authenticated connection — so the
// Bind is sent into the session lib/pq opened, holding the statement lib/pq
// parsed, and not into a second session that merely resembles it.
//
// lib/pq itself is imported from conformance_harness_test.go and nowhere else;
// this file reaches the driver through database/sql's "postgres" name, which
// that import registers.

import (
	"bytes"
	"crypto/tls"
	"database/sql"
	"encoding/binary"
	"fmt"
	"io"
	"net"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgproto3"
)

// unnamedTraceGolden is the committed record of the exchange below.
//
// IT IS NOT REGENERATED BY THE TEST RUN, for the same reason the lifecycle
// baseline is not: a trace a test rewrites records whatever happened, which is
// the one thing a witness must not do. Editing it is a deliberate statement
// that the front door's frame exchange changed, and review reads it as one.
const unnamedTraceGolden = "testdata/libpq-unnamed-statement.txt"

// tapFrameCap bounds a single relayed frame. A tap that trusted the declared
// length would allocate whatever a malformed peer claimed; nothing in this
// exchange approaches a megabyte.
const tapFrameCap = 1 << 20

// tapDeadline bounds every read and write the relay performs. Without it a
// withheld frame hangs the relay goroutine until the whole test binary's
// timeout fires, which reports "test timed out" and names no call.
const tapDeadline = 60 * time.Second

// libpqTap is the plaintext front the driver connects to, and the TLS
// connection to the front door behind it.
type libpqTap struct {
	t         *testing.T
	ln        net.Listener
	frontDoor string

	ready  chan struct{}
	pumps  sync.WaitGroup
	client net.Conn

	mu      sync.Mutex
	backend net.Conn
	trace   []string
	rfq     int
	faults  []string
}

// startLibPQTap begins listening for the driver and returns the address it
// should dial.
func startLibPQTap(t *testing.T, frontDoorAddr string) *libpqTap {
	t.Helper()
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("opening the plaintext front for the driver: %v", err)
	}
	tp := &libpqTap{t: t, ln: ln, frontDoor: frontDoorAddr, ready: make(chan struct{})}
	t.Cleanup(func() {
		_ = ln.Close()
		tp.closeAll()
	})
	go tp.accept()
	return tp
}

func (tp *libpqTap) addr() string { return tp.ln.Addr().String() }

func (tp *libpqTap) fault(format string, args ...any) {
	tp.mu.Lock()
	tp.faults = append(tp.faults, fmt.Sprintf(format, args...))
	tp.mu.Unlock()
}

func (tp *libpqTap) record(line string) {
	tp.mu.Lock()
	tp.trace = append(tp.trace, line)
	tp.mu.Unlock()
}

func (tp *libpqTap) readyCount() int {
	tp.mu.Lock()
	defer tp.mu.Unlock()
	return tp.rfq
}

func (tp *libpqTap) closeAll() {
	tp.mu.Lock()
	c, b := tp.client, tp.backend
	tp.mu.Unlock()
	if c != nil {
		_ = c.Close()
	}
	if b != nil {
		_ = b.Close()
	}
}

// accept takes the driver's one connection and opens the matching TLS session
// to the front door.
//
// ONE CONNECTION AND NO MORE. database/sql is told to keep a single connection
// open, and a second arrival would mean the pool opened another session whose
// object store is empty — against which every assertion below would pass while
// proving nothing about the session that ran the query.
func (tp *libpqTap) accept() {
	c, err := tp.ln.Accept()
	if err != nil {
		return
	}
	tp.mu.Lock()
	tp.client = c
	tp.mu.Unlock()
	_ = c.SetDeadline(time.Now().Add(tapDeadline))

	go func() {
		extra, aerr := tp.ln.Accept()
		if aerr != nil {
			return
		}
		_ = extra.Close()
		tp.fault("the driver opened a second connection; every assertion here is about the " +
			"session that ran the parameterised query, and a second session would be empty")
	}()

	backend, err := tp.dialFrontDoor()
	if err != nil {
		tp.fault("reaching the front door: %v", err)
		_ = c.Close()
		close(tp.ready)
		return
	}
	tp.mu.Lock()
	tp.backend = backend
	tp.mu.Unlock()
	close(tp.ready)

	tp.pumps.Add(2)
	go tp.pumpToFrontDoor(c, backend)
	go tp.pumpToDriver(c, backend)
}

// dialFrontDoor performs the TLS negotiation the driver is being spared.
func (tp *libpqTap) dialFrontDoor() (net.Conn, error) {
	raw, err := net.DialTimeout("tcp", tp.frontDoor, 10*time.Second)
	if err != nil {
		return nil, err
	}
	_ = raw.SetDeadline(time.Now().Add(tapDeadline))
	if _, err := raw.Write(sslRequest()); err != nil {
		_ = raw.Close()
		return nil, fmt.Errorf("asking for TLS: %w", err)
	}
	var answer [1]byte
	if _, err := io.ReadFull(raw, answer[:]); err != nil {
		_ = raw.Close()
		return nil, fmt.Errorf("reading the TLS answer: %w", err)
	}
	if answer[0] != 'S' {
		_ = raw.Close()
		return nil, fmt.Errorf("the front door answered %q to SSLRequest, want \"S\"", answer[0])
	}
	// InsecureSkipVerify: the listener under test issues its own self-signed
	// material per test. Verification has its own cells; this one is about what
	// the frames say.
	tlsConn := tls.Client(raw, &tls.Config{InsecureSkipVerify: true})
	if err := tlsConn.Handshake(); err != nil {
		_ = raw.Close()
		return nil, fmt.Errorf("the TLS handshake: %w", err)
	}
	_ = tlsConn.SetDeadline(time.Now().Add(tapDeadline))
	return tlsConn, nil
}

// pumpToFrontDoor relays what the driver sends, recording each frame.
func (tp *libpqTap) pumpToFrontDoor(client, backend net.Conn) {
	defer tp.pumps.Done()

	// The startup packet carries no type byte: a length, then the body. Every
	// later frame from the driver is typed, so this shape is read exactly once.
	var length [4]byte
	if _, err := io.ReadFull(client, length[:]); err != nil {
		tp.fault("reading the driver's startup length: %v", err)
		return
	}
	n := binary.BigEndian.Uint32(length[:])
	if n < 8 || n > tapFrameCap {
		tp.fault("the driver's startup packet declared %d bytes", n)
		return
	}
	body := make([]byte, n-4)
	if _, err := io.ReadFull(client, body); err != nil {
		tp.fault("reading the driver's startup packet: %v", err)
		return
	}
	tp.record("driver -> front door  " + renderStartup(body))
	if _, err := backend.Write(append(length[:], body...)); err != nil {
		tp.fault("forwarding the startup packet: %v", err)
		return
	}

	for {
		typ, frame, err := readTapFrame(client)
		if err != nil {
			return // the driver went idle and the test took the connection over
		}
		tp.record("driver -> front door  " + renderDriverFrame(typ, frame))
		if _, err := backend.Write(tapFrameBytes(typ, frame)); err != nil {
			return
		}
	}
}

// pumpToDriver relays the front door's answers, recording each frame and
// counting the readiness bytes so the test knows when the query is finished.
func (tp *libpqTap) pumpToDriver(client, backend net.Conn) {
	defer tp.pumps.Done()
	for {
		typ, frame, err := readTapFrame(backend)
		if err != nil {
			return
		}
		tp.record("front door -> driver  " + renderFrontDoorFrame(typ, frame))
		if typ == 'Z' {
			tp.mu.Lock()
			tp.rfq++
			tp.mu.Unlock()
		}
		if _, err := client.Write(tapFrameBytes(typ, frame)); err != nil {
			return
		}
	}
}

// takeOver stops the relay and hands back the connection the driver
// authenticated on.
//
// THE DEADLINES ARE THE STOP SIGNAL because both relay goroutines are parked
// inside a socket read, where a channel is never looked at. Setting a deadline
// in the past unblocks them; nothing is lost because the driver is idle and the
// front door answers only what it is asked.
func (tp *libpqTap) takeOver() net.Conn {
	tp.t.Helper()
	<-tp.ready
	tp.mu.Lock()
	client, backend := tp.client, tp.backend
	tp.mu.Unlock()
	if backend == nil {
		tp.t.Fatalf("the tap never reached the front door: %s", strings.Join(tp.faultList(), "; "))
	}
	past := time.Now().Add(-time.Second)
	_ = client.SetReadDeadline(past)
	_ = backend.SetReadDeadline(past)
	tp.pumps.Wait()
	_ = backend.SetDeadline(time.Now().Add(tapDeadline))
	return backend
}

func (tp *libpqTap) faultList() []string {
	tp.mu.Lock()
	defer tp.mu.Unlock()
	return append([]string(nil), tp.faults...)
}

func (tp *libpqTap) traceLines() []string {
	tp.mu.Lock()
	defer tp.mu.Unlock()
	return append([]string(nil), tp.trace...)
}

// readTapFrame reads exactly one typed protocol frame.
//
// EXACTLY ONE, never a buffered read-ahead: when the relay stops, the test
// keeps reading from the same socket, and a byte the relay had swallowed into a
// buffer would be a frame the test never sees.
func readTapFrame(r io.Reader) (byte, []byte, error) {
	var header [5]byte
	if _, err := io.ReadFull(r, header[:]); err != nil {
		return 0, nil, err
	}
	n := binary.BigEndian.Uint32(header[1:5])
	if n < 4 || n > tapFrameCap {
		return 0, nil, fmt.Errorf("frame %q declared %d bytes", header[0], n)
	}
	body := make([]byte, n-4)
	if _, err := io.ReadFull(r, body); err != nil {
		return 0, nil, err
	}
	return header[0], body, nil
}

func tapFrameBytes(typ byte, body []byte) []byte {
	out := make([]byte, 5+len(body))
	out[0] = typ
	binary.BigEndian.PutUint32(out[1:5], uint32(len(body)+4))
	copy(out[5:], body)
	return out
}

// renderStartup prints the startup packet's parameters in a fixed order.
//
// SORTED, because the driver builds them from a map and the wire order is
// therefore whatever the runtime chose this time. An unsorted rendering would
// make the committed trace fail at random.
func renderStartup(body []byte) string {
	if len(body) < 4 {
		return "Startup (truncated)"
	}
	version := binary.BigEndian.Uint32(body[:4])
	var params []string
	for _, field := range bytes.Split(body[4:], []byte{0}) {
		if len(field) == 0 {
			continue
		}
		params = append(params, string(field))
	}
	var pairs []string
	for i := 0; i+1 < len(params); i += 2 {
		pairs = append(pairs, params[i]+"="+params[i+1])
	}
	sort.Strings(pairs)
	return fmt.Sprintf("Startup(%d.%d) %s", version>>16, version&0xffff, strings.Join(pairs, " "))
}

// renderDriverFrame names a frame the client sent.
//
// THE TYPE BYTE ALONE IS AMBIGUOUS: 'D' is Describe from a client and DataRow
// from a server, 'C' is Close and CommandComplete, 'E' is Execute and
// ErrorResponse, 'S' is Sync and ParameterStatus. Direction is what
// disambiguates them, so there are two renderers and never one.
func renderDriverFrame(typ byte, body []byte) string {
	switch typ {
	case 'P':
		var m pgproto3.Parse
		if err := m.Decode(body); err != nil {
			return "Parse (undecodable)"
		}
		return fmt.Sprintf("Parse statement=%q query=%q param-oids=%v", m.Name, m.Query, m.ParameterOIDs)
	case 'B':
		var m pgproto3.Bind
		if err := m.Decode(body); err != nil {
			return "Bind (undecodable)"
		}
		return fmt.Sprintf("Bind portal=%q statement=%q params=%s result-formats=%v",
			m.DestinationPortal, m.PreparedStatement, renderParams(m.Parameters, m.ParameterFormatCodes),
			m.ResultFormatCodes)
	case 'D':
		var m pgproto3.Describe
		if err := m.Decode(body); err != nil {
			return "Describe (undecodable)"
		}
		return fmt.Sprintf("Describe kind=%q name=%q", m.ObjectType, m.Name)
	case 'E':
		var m pgproto3.Execute
		if err := m.Decode(body); err != nil {
			return "Execute (undecodable)"
		}
		return fmt.Sprintf("Execute portal=%q max-rows=%d", m.Portal, m.MaxRows)
	case 'C':
		var m pgproto3.Close
		if err := m.Decode(body); err != nil {
			return "Close (undecodable)"
		}
		return fmt.Sprintf("Close kind=%q name=%q", m.ObjectType, m.Name)
	case 'Q':
		var m pgproto3.Query
		if err := m.Decode(body); err != nil {
			return "Query (undecodable)"
		}
		return fmt.Sprintf("Query %q", m.String)
	case 'S':
		return "Sync"
	case 'H':
		return "Flush"
	case 'X':
		return "Terminate"
	case 'p':
		// The credential is never rendered. A committed artifact is read by
		// more people than the session it records, and the secret is not the
		// part that proves anything.
		return "PasswordMessage (redacted)"
	}
	return fmt.Sprintf("client frame %q (%d bytes)", typ, len(body))
}

// renderFrontDoorFrame names a frame the server sent.
func renderFrontDoorFrame(typ byte, body []byte) string {
	switch typ {
	case 'R':
		if len(body) >= 4 {
			return fmt.Sprintf("Authentication(%d)", binary.BigEndian.Uint32(body[:4]))
		}
		return "Authentication (truncated)"
	case 'S':
		// The NAME only. The values are the target server's own — its version
		// string, its time zone, its float digits — so a committed trace
		// carrying them would fail on the next PostgreSQL build. That the
		// values are relayed faithfully is asserted by the startup GUC cells.
		var m pgproto3.ParameterStatus
		if err := m.Decode(body); err != nil {
			return "ParameterStatus (undecodable)"
		}
		return fmt.Sprintf("ParameterStatus %s=<value>", m.Name)
	case 'K':
		// The process id and the cancel secret vary per connection.
		return "BackendKeyData (pid and secret vary per connection)"
	case 'Z':
		var m pgproto3.ReadyForQuery
		if err := m.Decode(body); err != nil {
			return "ReadyForQuery (undecodable)"
		}
		return fmt.Sprintf("ReadyForQuery %q", m.TxStatus)
	case '1':
		return "ParseComplete"
	case '2':
		return "BindComplete"
	case '3':
		return "CloseComplete"
	case 'n':
		return "NoData"
	case 'I':
		return "EmptyQueryResponse"
	case 't':
		var m pgproto3.ParameterDescription
		if err := m.Decode(body); err != nil {
			return "ParameterDescription (undecodable)"
		}
		return fmt.Sprintf("ParameterDescription oids=%v", m.ParameterOIDs)
	case 'T':
		var m pgproto3.RowDescription
		if err := m.Decode(body); err != nil {
			return "RowDescription (undecodable)"
		}
		var fields []string
		for _, f := range m.Fields {
			fields = append(fields, fmt.Sprintf("%s:oid=%d:fmt=%d", f.Name, f.DataTypeOID, f.Format))
		}
		return "RowDescription " + strings.Join(fields, " ")
	case 'D':
		var m pgproto3.DataRow
		if err := m.Decode(body); err != nil {
			return "DataRow (undecodable)"
		}
		var values []string
		for _, v := range m.Values {
			if v == nil {
				values = append(values, "NULL")
				continue
			}
			values = append(values, fmt.Sprintf("%q", string(v)))
		}
		return "DataRow " + strings.Join(values, " ")
	case 'C':
		var m pgproto3.CommandComplete
		if err := m.Decode(body); err != nil {
			return "CommandComplete (undecodable)"
		}
		return fmt.Sprintf("CommandComplete %q", string(m.CommandTag))
	case 'E':
		var m pgproto3.ErrorResponse
		if err := m.Decode(body); err != nil {
			return "ErrorResponse (undecodable)"
		}
		return fmt.Sprintf("ErrorResponse S=%q C=%q M=%q D=%q", m.Severity, m.Code, m.Message, m.Detail)
	case 'N':
		var m pgproto3.NoticeResponse
		if err := m.Decode(body); err != nil {
			return "NoticeResponse (undecodable)"
		}
		return fmt.Sprintf("NoticeResponse S=%q C=%q M=%q", m.Severity, m.Code, m.Message)
	}
	return fmt.Sprintf("server frame %q (%d bytes)", typ, len(body))
}

func renderParams(values [][]byte, formats []int16) string {
	var out []string
	for i, v := range values {
		format := int16(0)
		switch {
		case len(formats) == 1:
			format = formats[0]
		case i < len(formats):
			format = formats[i]
		}
		if v == nil {
			out = append(out, "NULL")
			continue
		}
		out = append(out, fmt.Sprintf("%q/fmt=%d", string(v), format))
	}
	if len(out) == 0 {
		return "(none)"
	}
	return strings.Join(out, ",")
}

// A LIVE lib/pq PARAMETERISED CALL, PAUSED AT READINESS, THEN A BIND OF THE
// UNNAMED STATEMENT WITH NO NEW PARSE.
//
// The mutation that reddens this: make the extended path's Sync handling call
// the object store's dropUnnamed instead of dropAllPortals, in
// core/exec/wire_extended.go. The unnamed statement then disappears at the
// readiness boundary, the Bind below is refused, and the failure message names
// the manufactured 26000. That control was run; see the trace artifact's
// footer.
func TestLibPQ_TheUnnamedStatementIsBindableAfterReadyForQuery(t *testing.T) {
	addr, secret, database, _ := pgLoopWithEngine(t)
	tap := startLibPQTap(t, addr)

	host, port, ok := strings.Cut(tap.addr(), ":")
	if !ok {
		t.Fatalf("the tap address %q is not host:port", tap.addr())
	}
	// sslmode=disable reaches the TAP, not the front door: the tap is the thing
	// that speaks TLS onward. The front door still refuses plaintext, and its
	// own cells prove that.
	db, err := sql.Open("postgres", fmt.Sprintf(
		"host=%s port=%s user=root password=%s dbname=%s sslmode=disable",
		host, port, secret, database))
	if err != nil {
		t.Fatalf("opening the driver against the tap: %v", err)
	}
	defer func() { _ = db.Close() }()
	// ONE connection, and no Ping: a Ping is a simple Query, and a simple Query
	// destroys the unnamed statement by protocol rule. The parameterised call
	// below has to be the last thing the driver sends.
	db.SetMaxOpenConns(1)

	var got int
	if err := db.QueryRowContext(opCtx(t), "SELECT $1::int + 1", 41).Scan(&got); err != nil {
		t.Fatalf("the driver's parameterised query failed: %v\ntrace so far:\n%s",
			err, strings.Join(tap.traceLines(), "\n"))
	}
	if got != 42 {
		t.Fatalf("the driver read %d, want 42", got)
	}

	// PAUSED AT READINESS, and the pause is verified rather than assumed. The
	// driver reads the final readiness byte itself before returning the row, so
	// three of them have crossed the tap by now: one for the session, one for
	// the Parse segment, one for the Bind/Execute segment.
	waitForReadiness(t, tap, 3)

	beforeTakeover := len(tap.traceLines())
	backend := tap.takeOver()
	fe := pgproto3.NewFrontend(backend, backend)

	// NO PARSE. That is the whole claim: the statement named "" is the one the
	// driver left behind, and binding it is legal protocol.
	bind := &pgproto3.Bind{
		DestinationPortal:    "",
		PreparedStatement:    "",
		ParameterFormatCodes: []int16{0},
		Parameters:           [][]byte{[]byte("100")},
		ResultFormatCodes:    []int16{0},
	}
	execute := &pgproto3.Execute{Portal: "", MaxRows: 0}
	tap.record("driver -> front door  " + renderDriverFrame('B', encodeForTrace(t, bind)))
	tap.record("driver -> front door  " + renderDriverFrame('E', encodeForTrace(t, execute)))
	tap.record("driver -> front door  Sync")
	fe.Send(bind)
	fe.Send(execute)
	fe.Send(&pgproto3.Sync{})
	if err := fe.Flush(); err != nil {
		t.Fatalf("sending the Bind of the unnamed statement: %v", err)
	}

	var (
		rows      []string
		refusals  []string
		completed string
	)
	for {
		msg, err := fe.Receive()
		if err != nil {
			t.Fatalf("reading the answer to a Bind of the unnamed statement: %v\ntrace:\n%s",
				err, strings.Join(tap.traceLines(), "\n"))
		}
		switch m := msg.(type) {
		case *pgproto3.ErrorResponse:
			tap.record("front door -> driver  " + fmt.Sprintf(
				"ErrorResponse S=%q C=%q M=%q D=%q", m.Severity, m.Code, m.Message, m.Detail))
			refusals = append(refusals, fmt.Sprintf("%s %s: %s (%s)", m.Severity, m.Code, m.Message, m.Detail))
		case *pgproto3.BindComplete:
			tap.record("front door -> driver  BindComplete")
		case *pgproto3.DataRow:
			var values []string
			for _, v := range m.Values {
				values = append(values, string(v))
			}
			rows = append(rows, strings.Join(values, "|"))
			tap.record("front door -> driver  DataRow " + fmt.Sprintf("%q", strings.Join(values, "|")))
		case *pgproto3.CommandComplete:
			completed = string(m.CommandTag)
			tap.record("front door -> driver  " + fmt.Sprintf("CommandComplete %q", completed))
		case *pgproto3.ReadyForQuery:
			tap.record("front door -> driver  " + fmt.Sprintf("ReadyForQuery %q", m.TxStatus))
			if m.TxStatus != 'I' {
				t.Errorf("the session ended the segment in transaction status %q, want idle", m.TxStatus)
			}
		default:
			tap.record(fmt.Sprintf("front door -> driver  %T", msg))
		}
		if _, done := msg.(*pgproto3.ReadyForQuery); done {
			break
		}
	}

	if len(refusals) > 0 {
		t.Fatalf("a Bind of the unnamed statement was refused: %s\n\n"+
			"lib/pq's query path prepares into the empty statement name and never closes it, so "+
			"the statement is live at this readiness boundary and the client is entitled to bind "+
			"it. A refusal here is the front door inventing a client bug — and if the code is "+
			"26000 the client is told it never parsed a statement it did parse.\n\ntrace:\n%s",
			strings.Join(refusals, "; "), strings.Join(tap.traceLines(), "\n"))
	}
	if len(rows) != 1 || rows[0] != "101" {
		t.Fatalf("the re-bound statement produced %v, want one row \"101\" — a different value "+
			"from the driver's own 42, so the row proves the statement was re-executed at the "+
			"TARGET with the new parameter rather than replayed from anything cached",
			rows)
	}
	if completed != "SELECT 1" {
		t.Errorf("command tag = %q, want \"SELECT 1\"", completed)
	}
	if faults := tap.faultList(); len(faults) > 0 {
		t.Fatalf("the tap reported: %s", strings.Join(faults, "; "))
	}

	// THE PREMISE, ASSERTED RATHER THAN DESCRIBED. Everything above is only
	// interesting if the driver really did leave an unnamed statement behind:
	// if it had parsed into a NAME, or had closed what it parsed, the Bind
	// would have been binding something the test itself created.
	assertDriverLeftTheUnnamedStatement(t, tap.traceLines()[:beforeTakeover])

	compareTraceGolden(t, tap.traceLines())
}

// waitForReadiness blocks until the tap has relayed the given number of
// readiness bytes.
//
// BOUNDED, and a timeout here is a real finding rather than a flake: the driver
// has already returned the row, so every one of those bytes has been read by
// the driver and therefore must have crossed the tap.
func waitForReadiness(t *testing.T, tp *libpqTap, want int) {
	t.Helper()
	deadline := time.Now().Add(10 * time.Second)
	for time.Now().Before(deadline) {
		if tp.readyCount() >= want {
			return
		}
		time.Sleep(10 * time.Millisecond)
	}
	t.Fatalf("only %d of %d readiness bytes crossed the tap:\n%s",
		tp.readyCount(), want, strings.Join(tp.traceLines(), "\n"))
}

// assertDriverLeftTheUnnamedStatement reads the recorded frames and requires
// that the driver parsed into the empty name and closed nothing.
func assertDriverLeftTheUnnamedStatement(t *testing.T, lines []string) {
	t.Helper()
	parsedUnnamed := false
	for _, line := range lines {
		if !strings.HasPrefix(line, "driver -> front door") {
			continue
		}
		if strings.Contains(line, `Parse statement=""`) {
			parsedUnnamed = true
		}
		if strings.Contains(line, "Close kind=") {
			t.Errorf("the driver sent %q — this cell's whole subject is a statement the driver "+
				"leaves behind, and a driver that closed it would make the Bind above a test of "+
				"nothing", strings.TrimSpace(line))
		}
	}
	if !parsedUnnamed {
		t.Fatalf("the driver never parsed into the empty statement name, so the Bind above bound "+
			"something this test created rather than something the driver left:\n%s",
			strings.Join(lines, "\n"))
	}
}

// compareTraceGolden holds the recorded exchange against the committed one.
func compareTraceGolden(t *testing.T, lines []string) {
	t.Helper()
	path := filepath.Join(repoRoot(t), "frontdoor", unnamedTraceGolden)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading the committed trace at %s: %v\n\nobserved:\n%s",
			path, err, strings.Join(lines, "\n"))
	}
	var want []string
	for _, line := range strings.Split(string(raw), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		want = append(want, trimmed)
	}
	got := make([]string, 0, len(lines))
	for _, line := range lines {
		got = append(got, strings.Join(strings.Fields(line), " "))
	}
	for i, w := range want {
		w = strings.Join(strings.Fields(w), " ")
		if i >= len(got) {
			t.Fatalf("the exchange stopped after %d frames; the committed trace expects %q at "+
				"position %d.\n\nobserved:\n%s", len(got), w, i+1, strings.Join(got, "\n"))
		}
		if got[i] != w {
			t.Fatalf("frame %d of the exchange is\n  %s\nand the committed trace says\n  %s\n\n"+
				"Editing %s is a deliberate statement that the front door's frame exchange "+
				"changed; review it as one.\n\nobserved:\n%s",
				i+1, got[i], w, unnamedTraceGolden, strings.Join(got, "\n"))
		}
	}
	if len(got) != len(want) {
		t.Fatalf("the exchange carried %d frames and the committed trace records %d.\n\n"+
			"observed:\n%s", len(got), len(want), strings.Join(got, "\n"))
	}
}

// encodeForTrace renders a message the test is about to send in the same form
// the relay renders the driver's own frames, so the artifact reads as one
// exchange rather than as two notations.
func encodeForTrace(t *testing.T, msg pgproto3.FrontendMessage) []byte {
	t.Helper()
	encoded, err := msg.Encode(nil)
	if err != nil {
		t.Fatalf("encoding %T for the trace: %v", msg, err)
	}
	if len(encoded) < 5 {
		t.Fatalf("encoding %T produced %d bytes", msg, len(encoded))
	}
	return encoded[5:]
}

// AND THE ENTITLEMENT ENDS WHERE THE CLIENT ENDS IT.
//
// What must hold: once the client explicitly Closes the unnamed statement, a
// later Bind of it must be refused with 26000 — the code a real PostgreSQL
// sends for a statement name that does not exist — and the session must survive
// the refusal. What goes wrong otherwise: a front door that answered the Bind
// anyway would be serving an object the client destroyed, which is worse than
// the manufactured refusal the cell above forbids, because the client has no
// way to notice.
//
// WHY THIS IS NOT THE SAME CELL TWICE. The cell above can pass for a bad
// reason: a front door that never refused a Bind at all — that simply forwarded
// every one and let the target answer — would satisfy it while holding no
// notion of a statement's lifetime whatsoever. This is the other direction of
// the same predicate, so the pair only passes for a store that tracks when the
// statement exists AND when it stops existing.
//
// THE PREDICATE IS CURRENT STATE, AND IT IS RE-ENTRANT. That is the whole point
// of asserting both directions: a session holding the unnamed statement is not
// empty and cannot be moved, and the same session one Close later is empty
// again and can be. A rule phrased as "a session that has ever parsed is pinned
// for its life" would pass the cell above and fail this one.
func TestLibPQ_ClosingTheUnnamedStatementEndsTheEntitlement(t *testing.T) {
	addr, secret, database, _ := pgLoopWithEngine(t)
	tap := startLibPQTap(t, addr)

	host, port, ok := strings.Cut(tap.addr(), ":")
	if !ok {
		t.Fatalf("the tap address %q is not host:port", tap.addr())
	}
	db, err := sql.Open("postgres", fmt.Sprintf(
		"host=%s port=%s user=root password=%s dbname=%s sslmode=disable",
		host, port, secret, database))
	if err != nil {
		t.Fatalf("opening the driver against the tap: %v", err)
	}
	defer func() { _ = db.Close() }()
	db.SetMaxOpenConns(1)

	var got int
	if err := db.QueryRowContext(opCtx(t), "SELECT $1::int + 1", 41).Scan(&got); err != nil {
		t.Fatalf("the driver's parameterised query failed: %v", err)
	}
	waitForReadiness(t, tap, 3)

	backend := tap.takeOver()
	fe := pgproto3.NewFrontend(backend, backend)

	fe.Send(&pgproto3.Close{ObjectType: 'S', Name: ""})
	fe.Send(&pgproto3.Sync{})
	if err := fe.Flush(); err != nil {
		t.Fatalf("closing the unnamed statement: %v", err)
	}
	closed := false
	for {
		msg, err := fe.Receive()
		if err != nil {
			t.Fatalf("reading the answer to Close: %v", err)
		}
		if _, ok := msg.(*pgproto3.CloseComplete); ok {
			closed = true
		}
		if e, bad := msg.(*pgproto3.ErrorResponse); bad {
			t.Fatalf("closing the unnamed statement was refused %s: %s", e.Code, e.Message)
		}
		if _, done := msg.(*pgproto3.ReadyForQuery); done {
			break
		}
	}
	if !closed {
		t.Fatal("the front door never confirmed the Close of the unnamed statement")
	}

	fe.Send(&pgproto3.Bind{
		DestinationPortal:    "",
		PreparedStatement:    "",
		ParameterFormatCodes: []int16{0},
		Parameters:           [][]byte{[]byte("100")},
		ResultFormatCodes:    []int16{0},
	})
	fe.Send(&pgproto3.Execute{Portal: "", MaxRows: 0})
	fe.Send(&pgproto3.Sync{})
	if err := fe.Flush(); err != nil {
		t.Fatalf("binding the closed statement: %v", err)
	}
	var code string
	served := false
	for {
		msg, err := fe.Receive()
		if err != nil {
			t.Fatalf("reading the answer to a Bind of the closed statement: %v", err)
		}
		switch m := msg.(type) {
		case *pgproto3.ErrorResponse:
			code = m.Code
		case *pgproto3.DataRow:
			served = true
		}
		if _, done := msg.(*pgproto3.ReadyForQuery); done {
			break
		}
	}
	if served {
		t.Fatal("a Bind of a CLOSED statement produced a row — the front door served an object " +
			"the client had destroyed, and the client has no way to notice")
	}
	if code != "26000" {
		t.Fatalf("a Bind of a closed statement was answered %q, want 26000 — that is the code a "+
			"real PostgreSQL sends for a statement name that does not exist, and a driver's "+
			"recovery is written against it", code)
	}

	// AND THE SESSION SURVIVES, which is what separates a refused frame from a
	// refused session: the client is expected to Parse again and carry on.
	fe.Send(&pgproto3.Parse{Name: "", Query: "SELECT 7"})
	fe.Send(&pgproto3.Bind{DestinationPortal: "", PreparedStatement: ""})
	fe.Send(&pgproto3.Execute{Portal: "", MaxRows: 0})
	fe.Send(&pgproto3.Sync{})
	if err := fe.Flush(); err != nil {
		t.Fatalf("re-parsing after the refusal: %v", err)
	}
	var value string
	for {
		msg, err := fe.Receive()
		if err != nil {
			t.Fatalf("reading the answer to the re-Parse: %v", err)
		}
		switch m := msg.(type) {
		case *pgproto3.ErrorResponse:
			t.Fatalf("the session did not survive the refusal: %s %s", m.Code, m.Message)
		case *pgproto3.DataRow:
			if len(m.Values) == 1 {
				value = string(m.Values[0])
			}
		}
		if _, done := msg.(*pgproto3.ReadyForQuery); done {
			break
		}
	}
	if value != "7" {
		t.Fatalf("the re-parsed statement returned %q, want \"7\"", value)
	}
	if faults := tap.faultList(); len(faults) > 0 {
		t.Fatalf("the tap reported: %s", strings.Join(faults, "; "))
	}
}
