package frontdoor

import (
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"net"
	"os"
	"regexp"
	"sort"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgproto3"

	"github.com/yongjohnlee80/autodb/core/exec"
)

// THE LIFECYCLE BASELINE.
//
// The connection lifecycle is about to be moved behind an outcome registry and
// a phase runner, and that refactor is required to be reviewable as a NO-OP. A
// no-op proof needs something to be no-op AGAINST, and the front door has
// never had one: there are conformance cells and denial-taxonomy cells in
// abundance, but they are distributed, and "all the existing tests still pass"
// is a weaker claim than it sounds. A test suite proves the
// properties somebody thought to assert. It does not notice that an event
// moved, that a charge changed hands, or that a socket now closes without the
// frame it used to send -- unless a cell happened to look.
//
// So this file captures what the lifecycle ACTUALLY DOES, per scenario, as a
// single canonical trace: the bytes on the wire including the paths that
// deliberately send none, the ordered events, the close reason, the charge
// delta against the per-source throttle, the resource accounting afterwards,
// and the calls made to the engine.
//
// IT IS CAPTURED AT THIS PARENT DELIBERATELY: after the panic containment and
// the charge split, so the charges here are the corrected ones. Taken before
// them, the baseline would have frozen the classification that treated a full
// connection pool as a failed login, and the refactor would then have been
// proven to preserve it faithfully.
//
// THE GOLDEN FILE IS NOT REGENERATED BY THIS TEST, and there is no flag that
// makes it. A baseline a failing run can rewrite is not a baseline, it is
// self-approval: the thing that drifted would be blessing the drift. Changing
// testdata/lifecycle-baseline.txt is a hand edit that shows up in review as
// what it is -- a change to the front door's observable behaviour. The
// semantic assertions in TestLifecycleBaseline_SemanticControls sit beside the
// diff for the same reason: a trace nobody can read still has to be checked
// against claims somebody wrote down.
//
// docs/front-door/lifecycle-baseline.md is the full account.

const baselineGolden = "testdata/lifecycle-baseline.txt"

// traceEngine is the engine seam for these scenarios, recording every call
// across BOTH interfaces in ONE order.
//
// One order matters: the existing fakes each record their own calls, so a
// change that moved the cancel-key registration to the other side of the
// session open would leave both per-interface logs unchanged. The thing this
// baseline has to notice is exactly that kind of move.
type traceEngine struct {
	mu    sync.Mutex
	calls []string

	session    exec.WireSessionResult
	openErr    error
	cancelsKey bool
}

func (e *traceEngine) note(format string, args ...any) {
	e.mu.Lock()
	e.calls = append(e.calls, fmt.Sprintf(format, args...))
	e.mu.Unlock()
}

func (e *traceEngine) log() []string {
	e.mu.Lock()
	defer e.mu.Unlock()
	return append([]string(nil), e.calls...)
}

func (e *traceEngine) OpenWireSession(ctx context.Context, presented, startupUser, database, ip string) (exec.WireSessionResult, error) {
	return e.OpenWireSessionWith(ctx, exec.WireOpen{
		PAT: presented, StartupUser: startupUser, Database: database, IP: ip,
	})
}

func (e *traceEngine) OpenWireSessionWith(ctx context.Context, req exec.WireOpen) (exec.WireSessionResult, error) {
	// THE CREDENTIAL IS NOT RECORDED, not even in a test artifact that is
	// about to be committed. What the trace needs is that an open happened
	// with this user, database and label; the token adds nothing and a golden
	// file full of credential-shaped strings teaches the wrong habit.
	_, hasDeadline := ctx.Deadline()
	e.note("Authn.OpenWireSessionWith user=%q db=%q app=%q bounded=%t",
		req.StartupUser, req.Database, req.ApplicationName, hasDeadline)
	if e.openErr != nil {
		return exec.WireSessionResult{}, e.openErr
	}
	res := e.session
	res.ApplicationName = req.ApplicationName
	return res, nil
}

func (e *traceEngine) CloseWireSession(_ context.Context, id exec.SessionID, _ int64, _, reason string) {
	e.note("Authn.CloseWireSession id=%q reason=%q", id, reason)
}

func (e *traceEngine) RegisterCancelKey(id exec.SessionID, _ int64, _ exec.CancelKey) error {
	// The PID and secret are a CSPRNG's output and differ every run, so the
	// trace records that a key was registered for this session and not which
	// key. A baseline containing a random number would fail on its second run
	// and teach everyone to regenerate it.
	e.note("Cancels.RegisterCancelKey id=%q", id)
	return nil
}

func (e *traceEngine) RevokeCancelKey(id exec.SessionID) {
	e.note("Cancels.RevokeCancelKey id=%q", id)
}

func (e *traceEngine) CancelByKey(context.Context, exec.CancelKey) bool {
	e.note("Cancels.CancelByKey -> %t", e.cancelsKey)
	return e.cancelsKey
}

// baselineScenario is one lifecycle path, driven from the client side.
type baselineScenario struct {
	name string
	why  string
	// opt is merged over the harness defaults.
	opt func(*traceEngine) Options
	// engine configures the scripted outcomes.
	engine func(*traceEngine)
	// prepare adjusts the listener's own state before anything connects.
	prepare func(*Listener)
	// awaitSession installs a session handler that signals once the handshake
	// has completed, and makes the harness wait for that signal before
	// afterDrive runs.
	awaitSession bool
	// drive talks to the listener and returns the SUBJECT connection's local
	// address together with everything the server sent it, having read to
	// EOF. Returning no bytes is a RESULT, not a failure: several of these
	// paths are required to answer nothing at all.
	//
	// The peer is returned because the event trail is per-LISTENER, and a
	// scenario that needs a second connection (one holding a cap open, say)
	// would otherwise interleave two lifecycles into one trace and make the
	// golden file depend on which goroutine ran first.
	drive func(t *testing.T, addr string) (peer string, wire []byte)
	// afterDrive runs once the client is done, for scenarios whose subject is
	// what the listener does next (shutdown).
	afterDrive func(t *testing.T, l *Listener)
}

// lifecycleScenarios are the paths a connection can take, in a fixed order so
// the golden file is stable: refused at accept, failed in TLS, refused at
// startup, cancelled (landing and not), abandoned mid-credential, denied,
// served and closed by the client, and served and closed by us.
//
// ONE PATH IS DELIBERATELY ABSENT, and its absence is a property rather than
// an oversight. A capacity refusal renders 53300 instead of the uniform denial
// only when it carries a witness that it was raised with a verified credential
// and a checked grant already in hand -- and the engine mints that witness at
// the raise site and nowhere else. There is no constructor for it, on purpose:
// one would let any caller forge the thing that decides whether the front door
// discloses live capacity to a stranger, which is exactly what the witness
// exists to prevent. That it cannot be forged BY A TEST EITHER is the property
// working, so this trace stops where a fake engine's reach stops.
// frontdoor/capacity_disclosure_test.go pins the disclosure itself.
func lifecycleScenarios() []baselineScenario {
	tlsOnly := func(e *traceEngine) Options {
		return Options{Authn: e, Cancels: e, AuthFailuresPerIP: unthrottled}
	}

	return []baselineScenario{
		{
			name: "accept-refusal-source-cap",
			why:  "one host holding its whole allowance is refused BEFORE a goroutine, a reader or a TLS buffer exists",
			opt:  tlsOnly,
			// LOWERED IN PLACE rather than through an option, because this is
			// a baseline commit and the point of it is that production code
			// does not move. The field is this package's own.
			prepare: func(l *Listener) {
				l.admit.mu.Lock()
				l.admit.maxPerSource = 1
				l.admit.mu.Unlock()
			},
			drive: func(t *testing.T, addr string) (string, []byte) {
				// The first connection holds the allowance open for the
				// second, which is the one being observed.
				held := dial(t, addr)
				defer func() { _ = held.Close() }()
				subject := dial(t, addr)
				return local(subject), readToEOF(t, subject)
			},
		},
		{
			name: "tls-failure",
			why:  "a peer speaking raw TLS cannot read a PostgreSQL error, so the refusal is a close and no frame",
			opt:  tlsOnly,
			drive: func(t *testing.T, addr string) (string, []byte) {
				c := dial(t, addr)
				if _, err := c.Write(sslRequest()); err != nil {
					t.Fatal(err)
				}
				answer := make([]byte, 1)
				if _, err := c.Read(answer); err != nil {
					t.Fatalf("SSL answer: %v", err)
				}
				// Garbage where a ClientHello belongs.
				if _, err := c.Write([]byte("this is not a TLS ClientHello")); err != nil {
					t.Fatal(err)
				}
				return local(c), append(answer, readToEOF(t, c)...)
			},
		},
		{
			name: "startup-failure-unsupported-major",
			why:  "a startup refused on policy never reaches the credential exchange",
			opt:  tlsOnly,
			drive: func(t *testing.T, addr string) (string, []byte) {
				tc := tlsDial(t, addr)
				if _, err := tc.Write(startupPacket(4<<16, defaultParams())); err != nil {
					t.Fatal(err)
				}
				return local(tc), readToEOF(t, tc)
			},
		},
		{
			name:   "cancel-stale",
			why:    "a cancel that resolves to nothing is answered by closing, never by a frame",
			opt:    tlsOnly,
			engine: func(e *traceEngine) { e.cancelsKey = false },
			drive:  driveCancel,
		},
		{
			name:   "cancel-applied",
			why:    "an applied cancel is answered exactly as a stale one is — the peer presented no credential",
			opt:    tlsOnly,
			engine: func(e *traceEngine) { e.cancelsKey = true },
			drive:  driveCancel,
		},
		{
			name: "auth-read-failure",
			why:  "a peer that leaves mid-exchange is charged; our own failures are not",
			opt:  tlsOnly,
			drive: func(t *testing.T, addr string) (string, []byte) {
				tc, fe := startupTo(t, addr, defaultParams())
				if _, err := fe.Receive(); err != nil {
					t.Fatalf("auth request: %v", err)
				}
				peer := local(tc)
				// Gone, without answering the prompt.
				_ = tc.Close()
				return peer, nil
			},
		},
		{
			name:   "auth-denied",
			why:    "the uniform denial: one shape for every credential outcome, charged to the source",
			opt:    tlsOnly,
			engine: func(e *traceEngine) { e.openErr = exec.WireDenial(exec.DenyBadCredential) },
			drive:  driveCredential,
		},
		{
			name:   "handshake-write-and-normal-close",
			why:    "the success sequence, then the client's Terminate",
			opt:    tlsOnly,
			engine: func(e *traceEngine) { e.session = goodSession() },
			drive: func(t *testing.T, addr string) (string, []byte) {
				tc, fe := startupTo(t, addr, defaultParams())
				if _, err := fe.Receive(); err != nil {
					t.Fatalf("auth request: %v", err)
				}
				fe.Send(&pgproto3.PasswordMessage{Password: "autodb_pat_secret"})
				if err := fe.Flush(); err != nil {
					t.Fatalf("credential: %v", err)
				}
				out := readThroughReady(t, tc)
				fe.Send(&pgproto3.Terminate{})
				if err := fe.Flush(); err != nil {
					t.Fatalf("terminate: %v", err)
				}
				return local(tc), append(out, readToEOF(t, tc)...)
			},
		},
		{
			name: "shutdown-with-a-live-session",
			// THE TRACE BELOW IS IDENTICAL TO THE NORMAL CLOSE, and that is a
			// finding rather than a coincidence: nothing on the shutdown path
			// sets a close reason, so handle falls through to its default and
			// the trail records "peer-closed" for a connection the SERVER
			// ended. An operator reading the audit after a deploy sees a
			// hundred clients that supposedly hung up.
			//
			// It is recorded, not fixed. This is the baseline commit; a
			// behaviour change here would be the one thing the refactor it
			// exists to check must not contain.
			why:    "Close ends a session the client has not ended — and the trail still says the peer did",
			opt:    tlsOnly,
			engine: func(e *traceEngine) { e.session = goodSession() },
			drive: func(t *testing.T, addr string) (string, []byte) {
				tc, fe := startupTo(t, addr, defaultParams())
				if _, err := fe.Receive(); err != nil {
					t.Fatalf("auth request: %v", err)
				}
				fe.Send(&pgproto3.PasswordMessage{Password: "autodb_pat_secret"})
				if err := fe.Flush(); err != nil {
					t.Fatalf("credential: %v", err)
				}
				return local(tc), readThroughReady(t, tc)
			},
			afterDrive:   func(t *testing.T, l *Listener) { l.Close() },
			awaitSession: true,
		},
	}
}

func driveCancel(t *testing.T, addr string) (string, []byte) {
	t.Helper()
	c := dial(t, addr)
	body := make([]byte, 16)
	binary.BigEndian.PutUint32(body[0:4], 16)
	binary.BigEndian.PutUint32(body[4:8], 80877102) // CancelRequest
	binary.BigEndian.PutUint32(body[8:12], 4242)    // pid
	binary.BigEndian.PutUint32(body[12:16], 9999)   // secret
	if _, err := c.Write(body); err != nil {
		t.Fatal(err)
	}
	return local(c), readToEOF(t, c)
}

func driveCredential(t *testing.T, addr string) (string, []byte) {
	t.Helper()
	tc, fe := startupTo(t, addr, defaultParams())
	if _, err := fe.Receive(); err != nil {
		t.Fatalf("auth request: %v", err)
	}
	fe.Send(&pgproto3.PasswordMessage{Password: "autodb_pat_secret"})
	if err := fe.Flush(); err != nil {
		t.Fatalf("credential: %v", err)
	}
	return local(tc), readToEOF(t, tc)
}

// local names the connection from the LISTENER's point of view: what the
// client calls its local address is the peer the event trail records.
func local(c net.Conn) string { return c.LocalAddr().String() }

// readToEOF reads until the server closes, and reports what it got. A clean
// EOF with nothing read is the answer on every silent path here.
func readToEOF(t *testing.T, c net.Conn) []byte {
	t.Helper()
	_ = c.SetReadDeadline(time.Now().Add(10 * time.Second))
	var out []byte
	buf := make([]byte, 4096)
	for {
		n, err := c.Read(buf)
		out = append(out, buf[:n]...)
		if err != nil {
			if !errors.Is(err, net.ErrClosed) && !isEOF(err) {
				// A TIMEOUT IS A RESULT WORTH FAILING ON. It means the server
				// neither answered nor closed, which is a different behaviour
				// from the silent close these paths promise -- and one a
				// trace recording "no bytes" would render identically.
				var ne net.Error
				if errors.As(err, &ne) && ne.Timeout() {
					t.Fatalf("the server neither answered nor closed within the deadline; "+
						"a hang is not the same outcome as a silent close (read %d bytes)", len(out))
				}
			}
			return out
		}
	}
}

func isEOF(err error) bool { return err != nil && err.Error() == "EOF" }

// readThroughReady reads the success sequence up to and including the first
// ReadyForQuery, so a scenario can continue afterwards.
func readThroughReady(t *testing.T, c net.Conn) []byte {
	t.Helper()
	_ = c.SetReadDeadline(time.Now().Add(10 * time.Second))
	var out []byte
	for {
		// Read the 5-byte header, then the body, so the stream is left
		// exactly after ReadyForQuery rather than inside the next message.
		hdr := make([]byte, 5)
		if _, err := ioReadFull(c, hdr); err != nil {
			t.Fatalf("reading a message header: %v", err)
		}
		n := int(binary.BigEndian.Uint32(hdr[1:5])) - 4
		body := make([]byte, n)
		if n > 0 {
			if _, err := ioReadFull(c, body); err != nil {
				t.Fatalf("reading a message body: %v", err)
			}
		}
		out = append(out, hdr...)
		out = append(out, body...)
		if hdr[0] == 'Z' {
			return out
		}
	}
}

func ioReadFull(c net.Conn, b []byte) (int, error) {
	total := 0
	for total < len(b) {
		n, err := c.Read(b[total:])
		total += n
		if err != nil {
			return total, err
		}
	}
	return total, nil
}

// renderTrace turns one scenario's observations into the canonical text.
func renderTrace(sc baselineScenario, wire []byte, events []Event, charge int, after string, calls []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "## %s\n", sc.name)
	fmt.Fprintf(&b, "# %s\n", sc.why)

	b.WriteString("wire:\n")
	for _, line := range describeWire(wire) {
		fmt.Fprintf(&b, "  %s\n", line)
	}

	b.WriteString("events:\n")
	closeReason := "(none)"
	for _, e := range events {
		if e.Kind == "fd.conn_close" {
			closeReason = e.Reason
		}
		line := "  " + e.Kind
		if e.Reason != "" {
			line += " reason=" + e.Reason
		}
		if e.Detail != "" {
			line += " detail=" + e.Detail
		}
		b.WriteString(line + "\n")
	}
	fmt.Fprintf(&b, "close-reason: %s\n", closeReason)
	fmt.Fprintf(&b, "charge-delta: %d\n", charge)
	fmt.Fprintf(&b, "resources-after: %s\n", after)

	b.WriteString("engine-calls:\n")
	if len(calls) == 0 {
		b.WriteString("  (none)\n")
	}
	for _, c := range calls {
		fmt.Fprintf(&b, "  %s\n", c)
	}
	return b.String()
}

// describeWire renders the server's output as NAMED FRAMES, not only hex.
//
// Hex alone would make the golden file unreadable, and an unreadable baseline
// is one nobody checks -- it gets regenerated. Naming the frames and the
// fields that are stable makes a diff say what changed rather than where.
func describeWire(b []byte) []string {
	if len(b) == 0 {
		return []string{"(no bytes — the server closed without writing)"}
	}
	var out []string
	i := 0
	// The SSL negotiation answer is a bare byte, outside the framed protocol.
	if b[0] == 'S' || b[0] == 'N' {
		out = append(out, fmt.Sprintf("ssl-answer %q", string(b[0])))
		i = 1
	}
	for i+5 <= len(b) {
		typ := b[i]
		n := int(binary.BigEndian.Uint32(b[i+1 : i+5]))
		if n < 4 || i+1+n > len(b) {
			out = append(out, fmt.Sprintf("truncated frame %q len=%d", string(typ), n))
			break
		}
		body := b[i+5 : i+1+n]
		out = append(out, describeFrame(typ, body))
		i += 1 + n
	}
	if i < len(b) {
		out = append(out, fmt.Sprintf("trailing %d byte(s)", len(b)-i))
	}
	return out
}

func describeFrame(typ byte, body []byte) string {
	switch typ {
	case 'E':
		return "ErrorResponse " + describeErrorFields(body)
	case 'R':
		if len(body) >= 4 {
			return fmt.Sprintf("Authentication(%d)", binary.BigEndian.Uint32(body[:4]))
		}
		return "Authentication(?)"
	case 'S':
		parts := strings.Split(strings.TrimRight(string(body), "\x00"), "\x00")
		if len(parts) == 2 {
			return fmt.Sprintf("ParameterStatus %s=%q", parts[0], parts[1])
		}
		return "ParameterStatus(?)"
	case 'K':
		// THE VALUES ARE DELIBERATELY NOT RECORDED. A BackendKeyData carries
		// a CSPRNG pid and secret; pinning them would make the baseline fail
		// on its second run, and a baseline that fails for a reason nobody
		// cares about is a baseline everyone regenerates.
		return "BackendKeyData (pid and secret vary per connection)"
	case 'Z':
		if len(body) == 1 {
			return fmt.Sprintf("ReadyForQuery %q", string(body[0]))
		}
		return "ReadyForQuery(?)"
	case 'v':
		return "NegotiateProtocolVersion"
	case 'N':
		return "NoticeResponse " + describeErrorFields(body)
	}
	return fmt.Sprintf("frame %q (%d bytes)", string(typ), len(body))
}

// describeErrorFields records the fields a CLIENT can see, in the protocol's
// own order, and nothing else.
func describeErrorFields(body []byte) string {
	var parts []string
	for _, f := range strings.Split(strings.TrimRight(string(body), "\x00"), "\x00") {
		if f == "" {
			continue
		}
		code, value := f[0], f[1:]
		switch code {
		case 'S', 'V', 'C', 'M', 'D':
			parts = append(parts, fmt.Sprintf("%s=%q", string(code), value))
		default:
			parts = append(parts, fmt.Sprintf("%s=<present>", string(code)))
		}
	}
	return strings.Join(parts, " ")
}

// runScenario drives one scenario and returns its canonical trace.
func runScenario(t *testing.T, sc baselineScenario) string {
	t.Helper()
	eng := &traceEngine{}
	if sc.engine != nil {
		sc.engine(eng)
	}
	opt := sc.opt(eng)
	inSession := make(chan struct{})
	if sc.awaitSession {
		var once sync.Once
		// BEHAVES AS THE DEFAULT HANDLER DOES -- it reads until the connection
		// ends -- and signals first. Substituting it changes no observable
		// behaviour for a client that sends nothing after its readiness, which
		// is what the golden proves by not moving.
		opt.OnSession = func(_ context.Context, _ net.Conn, be *pgproto3.Backend, _ exec.WireSessionResult) error {
			once.Do(func() { close(inSession) })
			for {
				if _, err := be.Receive(); err != nil {
					return nil
				}
			}
		}
	}
	// PREPARE RUNS BEFORE Serve. Applying it afterwards is a write to a field
	// the accept loop is already reading -- the source-cap scenario lowers
	// exactly such a field -- and the race detector reports it as
	// indistinguishable from a production race.
	l, events, addr := listenerWithPrepare(t, opt, sc.prepare)

	host := "127.0.0.1"
	before := failureCount(l, host)

	peer, wire := sc.drive(t, addr)
	if sc.awaitSession {
		// PAST THE FORK. The handler runs only after the handshake phase has
		// armed the idle deadline, so Close below cannot land on the near side
		// of it and produce the other of the two correct endings.
		select {
		case <-inSession:
		case <-time.After(5 * time.Second):
			t.Fatal("the session handler never ran, so the shutdown barrier proves nothing")
		}
	}
	if sc.afterDrive != nil {
		sc.afterDrive(t, l)
	}
	mine := func() []Event {
		var out []Event
		for _, e := range events() {
			if e.Peer == peer {
				out = append(out, e)
			}
		}
		return out
	}

	// The close event is emitted by the connection's own goroutine after the
	// client is gone, so waiting for it is not optional -- reading the trail
	// immediately would capture a lifecycle missing its last line, and the
	// baseline would then pin a truncation.
	// A TERMINAL EVENT, and there are two kinds. A connection refused at
	// accept never enters handle, so it emits fd.budget_refuse and no
	// fd.conn_close -- waiting only for the close would hang on exactly the
	// path whose whole point is that it costs nothing.
	waitFor(t, "the connection's terminal event", func() bool {
		for _, e := range mine() {
			if e.Kind == "fd.conn_close" || e.Kind == "fd.budget_refuse" {
				return true
			}
		}
		return false
	})
	waitFor(t, "the accept-time reservation to be released", func() bool {
		return liveConns(l) == 0
	})

	// THE SUBJECT'S EVENTS ONLY, and the count is asserted: a scenario whose
	// peer never appears would render an empty trail, and an empty trail
	// diffs cleanly against an empty expectation forever.
	own := mine()
	if len(own) == 0 {
		t.Fatalf("no events were recorded for %s; the trace would be vacuous", peer)
	}
	return renderTrace(sc, wire, normalizeEvents(own),
		failureCount(l, host)-before, resourcesAfter(l), eng.log())
}

// normalizeEvents drops the peer address, which carries an ephemeral port.
func normalizeEvents(in []Event) []Event {
	out := make([]Event, 0, len(in))
	for _, e := range in {
		e.Peer = ""
		e.Detail = portRE.ReplaceAllString(e.Detail, ":<port>")
		e.Reason = portRE.ReplaceAllString(e.Reason, ":<port>")
		out = append(out, e)
	}
	return out
}

var portRE = regexp.MustCompile(`:\d{4,5}\b`)

func failureCount(l *Listener, host string) int {
	l.admit.mu.Lock()
	defer l.admit.mu.Unlock()
	return len(l.admit.failures[host])
}

func liveConns(l *Listener) int {
	l.admit.mu.Lock()
	defer l.admit.mu.Unlock()
	return l.admit.conns
}

// resourcesAfter is the accounting once the connection is gone. Every number
// here must be zero: a ticket, a pre-auth slot, a control-lane reservation, a
// per-source entry and a tracking entry are all acquired on this path and all
// released on it, and the one that is not released is the one an anonymous
// peer can farm.
func resourcesAfter(l *Listener) string {
	l.admit.mu.Lock()
	conns, preAuth, lane := l.admit.conns, l.admit.preAuth, l.admit.laneUsed
	sources := make([]string, 0, len(l.admit.perSource))
	for h, n := range l.admit.perSource {
		sources = append(sources, fmt.Sprintf("%s=%d", h, n))
	}
	l.admit.mu.Unlock()
	sort.Strings(sources)

	l.liveMu.Lock()
	tracked := len(l.live)
	l.liveMu.Unlock()

	return fmt.Sprintf("conns=%d pre-auth=%d control-lane-bytes=%d per-source=[%s] tracked=%d",
		conns, preAuth, lane, strings.Join(sources, " "), tracked)
}

// TestLifecycleBaseline_MatchesTheRecordedTrace is the diff.
func TestLifecycleBaseline_MatchesTheRecordedTrace(t *testing.T) {
	var got strings.Builder
	got.WriteString(baselineHeader)
	for _, sc := range lifecycleScenarios() {
		got.WriteString("\n")
		got.WriteString(runScenario(t, sc))
	}

	want, err := os.ReadFile(baselineGolden)
	if err != nil {
		t.Fatalf("reading the baseline: %v\n\nThe recorded trace is not optional: the "+
			"no-op proof for the lifecycle refactor is a diff against it. If it is genuinely "+
			"missing, it must be reconstructed and REVIEWED, not regenerated from the run "+
			"that noticed it was gone. See docs/front-door/lifecycle-baseline.md.", err)
	}
	if diff := firstDifference(string(want), got.String()); diff != "" {
		t.Fatalf("the front door's observable lifecycle has changed.\n\n%s\n\n"+
			"This file is not regenerated by the test run and there is no flag that does it. "+
			"If the change is intended, edit %s by hand so the diff a reviewer reads is the "+
			"behaviour change itself.", diff, baselineGolden)
	}
}

// firstDifference reports the first differing line with its neighbours, which
// is what a reader needs; a whole-file dump of a trace this size is not a
// diff, it is a haystack.
func firstDifference(want, got string) string {
	wl, gl := strings.Split(want, "\n"), strings.Split(got, "\n")
	for i := 0; i < len(wl) || i < len(gl); i++ {
		w, g := "", ""
		if i < len(wl) {
			w = wl[i]
		}
		if i < len(gl) {
			g = gl[i]
		}
		if w == g {
			continue
		}
		var b strings.Builder
		fmt.Fprintf(&b, "first difference at line %d:\n", i+1)
		for j := max0(i - 4); j < i; j++ {
			fmt.Fprintf(&b, "   %s\n", wl[j])
		}
		fmt.Fprintf(&b, "  -%s\n", w)
		fmt.Fprintf(&b, "  +%s\n", g)
		for j := i + 1; j < i+4 && j < len(gl); j++ {
			fmt.Fprintf(&b, "   %s\n", gl[j])
		}
		return b.String()
	}
	return ""
}

func max0(n int) int {
	if n < 0 {
		return 0
	}
	return n
}

const baselineHeader = `# The front door's observable connection lifecycle, captured at the parent of
# the lifecycle refactor — after the panic containment and the charge split, so
# the charges below are the corrected ones.
#
# NOT REGENERATED BY THE TEST RUN. Editing this file is a deliberate statement
# that the front door's behaviour changed; review it as one.
#
# docs/front-door/lifecycle-baseline.md explains what is here and why.
`

// TestLifecycleBaseline_SemanticControls asserts the claims the trace is
// supposed to embody, in words, beside it.
//
// The diff alone is not enough and the ADR says why: a golden file proves that
// nothing changed, never that what it recorded was right. If the capture ever
// went wrong -- an empty read mistaken for a silent close, a charge counted
// against the wrong host -- the diff would defend the mistake forever. These
// cells fail on the CLAIM, so a wrong baseline and a changed baseline do not
// look the same.
func TestLifecycleBaseline_SemanticControls(t *testing.T) {
	traces := map[string]string{}
	for _, sc := range lifecycleScenarios() {
		traces[sc.name] = runScenario(t, sc)
	}

	get := func(name string) string {
		tr, ok := traces[name]
		if !ok {
			t.Fatalf("no trace for %q; the scenario set changed and these controls did not", name)
		}
		return tr
	}

	// SILENT PATHS ARE SILENT. A peer that has not negotiated TLS, or has
	// presented no credential, is answered by a close and nothing else --
	// writing a PostgreSQL error to a raw-TLS peer is unreadable bytes, and
	// answering a cancel at all would tell an anonymous peer whether their
	// guess landed.
	for _, name := range []string{"accept-refusal-source-cap", "cancel-stale", "cancel-applied"} {
		if !strings.Contains(get(name), "(no bytes") {
			t.Errorf("%s: the server wrote to a peer that is owed nothing:\n%s", name, get(name))
		}
	}
	if !strings.Contains(get("tls-failure"), "ssl-answer \"S\"\n") ||
		strings.Contains(get("tls-failure"), "ErrorResponse") {
		t.Errorf("tls-failure: the refusal carried a frame a raw-TLS peer cannot read:\n%s",
			get("tls-failure"))
	}

	// A CANCEL IS INDISTINGUISHABLE WHETHER OR NOT IT LANDED. The only
	// difference between these two lifecycles is the internal audit line and
	// the engine's answer; the wire, the close reason and the charge are the
	// same.
	stale, applied := get("cancel-stale"), get("cancel-applied")
	if wireOf(stale) != wireOf(applied) {
		t.Errorf("an applied cancel is distinguishable from a stale one on the wire:\n%s\nvs\n%s",
			wireOf(stale), wireOf(applied))
	}
	if !strings.Contains(stale, "fd.cancel_stale") || !strings.Contains(applied, "fd.cancel_applied") {
		t.Error("the applied/stale split vanished from the audit trail, which is the only " +
			"place it is allowed to exist")
	}

	// THE CHARGE SPLIT, which is the reason the 2026-09-15 lockout happened. A credential failure and a handshake
	// failure are the peer's; capacity is ours, and charging it banned a
	// developer for the system being full.
	for _, c := range []struct {
		name string
		want string
		why  string
	}{
		{"tls-failure", "charge-delta: 1", "handshake grinding is charged, or an attacker switches to it for a fresh allowance"},
		{"auth-denied", "charge-delta: 1", "a bad credential is the peer's doing"},
		{"auth-read-failure", "charge-delta: 1", "a peer that leaves mid-exchange is the peer"},
		{"startup-failure-unsupported-major", "charge-delta: 1", "a refused startup is the peer's doing"},
		{"accept-refusal-source-cap", "charge-delta: 0", "a connection refused for concurrency is not a failed credential"},
		{"cancel-stale", "charge-delta: 0", "a cancel presents no credential and cannot fail one"},
		{"handshake-write-and-normal-close", "charge-delta: 0", "a SUCCESSFUL login must never be charged, or every pool in the estate caps at ten a minute"},
	} {
		if !strings.Contains(get(c.name), c.want) {
			t.Errorf("%s: want %q — %s\n%s", c.name, c.want, c.why, get(c.name))
		}
	}

	// THE UNIFORM DENIAL, which is what every path here must render: without
	// the engine's authorization witness there is one shape for every cause,
	// so nobody can enumerate users or databases one connection at a time.
	if !strings.Contains(get("auth-denied"), `C="28000"`) ||
		!strings.Contains(get("auth-denied"), `M="authentication failed"`) {
		t.Errorf("the uniform denial changed shape:\n%s", get("auth-denied"))
	}
	// The disclosed half of the witness matrix lives in
	// capacity_disclosure_test.go, because the witness cannot be minted from
	// outside the engine -- see the note on lifecycleScenarios.

	// NOTHING IS LEAKED ON ANY PATH. The ticket, the pre-auth slot, the
	// control-lane reservation, the per-source entry and the tracking entry
	// are acquired on these paths and released on them; the one that is not
	// released is the one an anonymous peer farms by being refused.
	for name, tr := range traces {
		if !strings.Contains(tr, "resources-after: conns=0 pre-auth=0 control-lane-bytes=0 per-source=[] tracked=0") {
			t.Errorf("%s leaked an accept-time resource:\n%s", name, tr)
		}
	}

	// THE SHUTDOWN ATTRIBUTION, asserted as it currently IS so that changing
	// it is a decision somebody makes rather than a diff somebody accepts.
	// The server ends the connection and the trail says the peer did.
	if !strings.Contains(get("shutdown-with-a-live-session"), "close-reason: peer-closed") {
		t.Error("the shutdown close reason changed. If a listener-initiated close is now " +
			"distinguishable from a client hanging up, that is an IMPROVEMENT and this " +
			"control should be updated to require it — but not inside a refactor that is " +
			"supposed to change no behaviour")
	}
}

// wireOf returns just the wire section of a trace.
func wireOf(trace string) string {
	_, rest, ok := strings.Cut(trace, "wire:\n")
	if !ok {
		return ""
	}
	out, _, _ := strings.Cut(rest, "events:\n")
	return out
}

// THE FORK THE SHUTDOWN BARRIER CLOSES IS REAL, and this reaches the other
// branch on purpose.
//
// Between flushing the success sequence and arming the idle deadline there is
// a gap. A Close landing inside it makes the arming fail and the session end
// "deadline"; one landing after it makes the read fail and the session end
// "peer-closed". Both are correct behaviours and only one can be the recorded
// trace.
//
// The baseline picks the second by waiting until the server is demonstrably
// past the gap. That is only worth anything if the first is genuinely
// reachable -- otherwise the barrier is excluding nothing and the trace would
// be stable without it. So this cell steps into the gap and shows the other
// ending, which is what makes the barrier a choice rather than a hope.
func TestLifecycleBaseline_TheShutdownForkIsRealAndTheBarrierSelectsOne(t *testing.T) {
	t.Parallel()
	ctx := context.Background()

	atGap := make(chan struct{})
	release := make(chan struct{})
	var once sync.Once

	eng := &traceEngine{session: goodSession()}
	l, events, addr := listenerWith(t, Options{
		Authn: eng, Cancels: eng, AuthFailuresPerIP: unthrottled,
		testBeforeDeadlineArm: func() {
			once.Do(func() {
				close(atGap)
				<-release
			})
		},
	})
	_ = ctx

	tc, fe := startupTo(t, addr, defaultParams())
	if _, err := fe.Receive(); err != nil {
		t.Fatalf("auth request: %v", err)
	}
	fe.Send(&pgproto3.PasswordMessage{Password: "autodb_pat_secret"})
	if err := fe.Flush(); err != nil {
		t.Fatalf("credential: %v", err)
	}

	select {
	case <-atGap:
	case <-time.After(5 * time.Second):
		t.Fatal("the handshake never reached the gap between the flush and the arming")
	}

	// CLOSE THE SOCKET INSIDE THE GAP. Arming a deadline on a closed
	// connection fails, which is the branch this cell exists to reach.
	//
	// The tracked connection is closed DIRECTLY rather than through Close():
	// Close waits for in-flight handlers, and the handler it would wait for is
	// the one parked in this gap -- so calling it here deadlocks on itself.
	// Closing the live set is exactly what Close does to it, without the wait.
	l.liveMu.Lock()
	closed := len(l.live)
	for c := range l.live {
		_ = c.Close()
	}
	l.liveMu.Unlock()
	if closed == 0 {
		t.Fatal("no connection was tracked, so nothing was closed inside the gap")
	}
	close(release)
	_ = readToEOF(t, tc)

	waitFor(t, "the session to end", func() bool {
		for _, e := range events() {
			if e.Kind == "fd.session_close" {
				return true
			}
		}
		return false
	})

	var reason string
	for _, e := range events() {
		if e.Kind == "fd.session_close" {
			reason = e.Reason
		}
	}
	if reason != OutcomeDeadlineArm {
		t.Fatalf("session_close reason = %q, want %q. If this branch is unreachable the "+
			"shutdown barrier is excluding nothing, and the recorded trace would be stable "+
			"without it", reason, OutcomeDeadlineArm)
	}
}
